"""
lang_data.py — content bank for Language Lab (autism/language-lab.md).

Consumed by _tools/build-language-lab.py, which packs it as JSON and encrypts
it into the page front matter. The game engine lives in
_layouts/protected-lang.html — editing games there never requires
re-encryption; editing THIS file does (re-run build-language-lab.py).

Built for a young autistic learner who is a GESTALT LANGUAGE PROCESSOR and
HYPERLEXIC (reads fluently, comprehension lags). Design rules baked into the
content:

- Sentence Builder items model MITIGABLE GESTALTS (Natural Language
  Acquisition stage 2): reusable sentence frames ("Can I have ___",
  "I feel ___ because ___") that snap together with interchangeable endings.
  Foil combinations should be either funny-silly (hearing them read aloud is
  its own lesson in what doesn't work) or grammatical-but-wrong-for-the-scene.
- Picture Match options are EMOJI-ONLY (no captions) — pure receptive
  sentence-to-scene mapping; the caption appears only in the teach line and
  speech. "\\n" inside an option emoji renders as a line break (used for
  on/under/above spatial layouts).
- Robo Says items train following directions: attribute discrimination →
  two-step "first/then" → before/after and ordering (the classic receptive
  milestones). "any": True makes tap order free ("tap all the hearts").
- Say It Another Way targets the hyperlexic gap head-on: literal readers meet
  paraphrase, indirect speech, then idioms — every idiom has a literal-trap
  foil and a teach line naming it "a saying".
- Mind Movies stories carry a visualization prompt (Visualizing &
  Verbalizing style) and number-rich text (numbers are this kid's currency);
  questions climb literal → prediction/why → inference/"how do you know" →
  main idea.
- What Would You Say items are FUNCTIONAL SCRIPTS — each correct answer is a
  gestalt worth adopting (requesting, repair, self-advocacy, flexibility,
  kind honesty). The engine saves earned phrases to a personal Phrase Wall.

Schema
------
BUILD: list of dicts (Sentence Builder)
    lvl      : 1 | 2 | 3 (tier)
    scene    : emoji shown big above the situation
    situ     : one-or-two-sentence situation, read aloud
    starters : list of 3 starter chunks
    ends     : list of 3 ending chunks
    ok       : list of [starter_idx, end_idx] pairs that fit the scene
               (usually one; more when several combos genuinely work)
    teach    : line shown+spoken after success — names the frame and when
               to use it

MATCH: list of dicts (Picture Match)
    lvl  : 1 | 2 | 3
    sent : the sentence to understand
    opts : list of (emoji_scene, spoken_label, correct) — exactly one
           correct=1; emoji may contain "\\n" for vertical layouts
    teach: shown+spoken after answering

DIRS: list of dicts (Robo Says)
    lvl   : 1 | 2 | 3
    instr : the direction to follow (read aloud)
    items : list of (emoji, spoken_label) or (emoji, label, size) where
            size is "big" | "small" (rendered larger/smaller)
    seq   : list of item indices in required tap order
    any   : optional True — indices in seq may be tapped in any order
    fixed : optional True — keep items in listed order on screen (needed
            when the instruction uses positional words like first/last);
            otherwise the engine shuffles display positions
    teach : shown+spoken after the round step

SAME: list of dicts (Say It Another Way)
    lvl  : 1 | 2 | 3
    sent : the sentence/expression to interpret
    opts : list of (text, correct) — exactly one correct=1; text-only on
           purpose (he reads well; meaning is the work)
    teach: shown+spoken after answering

STORIES: list of dicts (Mind Movies)
    lvl   : 1 | 2 | 3
    title : story name
    emoji : cover emoji
    text  : 3–5 short sentences, number-rich
    qs    : list of {q, opts: [(text, correct)], teach}

SAY: list of dicts (What Would You Say?)
    lvl  : 1 | 2 | 3
    scene: emoji shown big
    situ : the situation, read aloud
    opts : list of (text, correct) — every option must be something a kid
           could actually say (the wrong ones teach by contrast)
    teach: shown+spoken after answering
"""

# ═══════════════════════ SENTENCE BUILDER ═══════════════════════

BUILD = [
    # ── Tier 1: first frames — request, comment, protest, need ──
    {"lvl": 1, "scene": "🥤", "situ": "You are thirsty.",
     "starters": ["Can I have", "I see", "Goodnight,"],
     "ends": ["some water, please?", "a big elephant.", "my shoes."],
     "ok": [[0, 0]],
     "teach": "'Can I have ___, please?' is how we ask for something we want."},
    {"lvl": 1, "scene": "🍪", "situ": "You want a cookie.",
     "starters": ["I want", "Let's go", "I hear"],
     "ends": ["a cookie, please.", "to sleep.", "a fire truck."],
     "ok": [[0, 0]],
     "teach": "'I want ___, please' tells people exactly what you want."},
    {"lvl": 1, "scene": "🚗", "situ": "You see a red car outside.",
     "starters": ["I see", "Can I eat", "Goodnight,"],
     "ends": ["a red car!", "the window?", "my chair."],
     "ok": [[0, 0]],
     "teach": "'I see ___!' shares what you notice. Sharing is talking too!"},
    {"lvl": 1, "scene": "🐕", "situ": "A big dog runs by.",
     "starters": ["Look at", "I smell", "Put on"],
     "ends": ["that big dog!", "the TV.", "my juice."],
     "ok": [[0, 0]],
     "teach": "'Look at ___!' invites someone to see what you see."},
    {"lvl": 1, "scene": "🧩", "situ": "The puzzle is too hard.",
     "starters": ["Help me", "I am eating", "Let's dance"],
     "ends": ["with my puzzle, please.", "under the bed.", "on the ceiling."],
     "ok": [[0, 0]],
     "teach": "'Help me with ___, please' gets you help fast."},
    {"lvl": 1, "scene": "🥦", "situ": "Mom gives you broccoli. You do not want it.",
     "starters": ["I don't like", "I love", "Where is"],
     "ends": ["broccoli.", "my bed.", "the rain?"],
     "ok": [[0, 0]],
     "teach": "'I don't like ___' says no with words — kind and clear."},
    {"lvl": 1, "scene": "🛝", "situ": "You want to go to the playground.",
     "starters": ["Let's go", "I taste", "Put away"],
     "ends": ["to the playground!", "the door.", "my nose."],
     "ok": [[0, 0]],
     "teach": "'Let's go ___' is for places you want to go together."},
    {"lvl": 1, "scene": "🧃", "situ": "Your cup is empty. You want more juice.",
     "starters": ["More", "Under", "Blue"],
     "ends": ["juice, please!", "the table.", "banana."],
     "ok": [[0, 0]],
     "teach": "'More ___, please!' works for ANYTHING you want again."},
    {"lvl": 1, "scene": "🛏️", "situ": "You are very sleepy.",
     "starters": ["I am", "Let's cook", "Open"],
     "ends": ["tired.", "the moon.", "my shoe."],
     "ok": [[0, 0]],
     "teach": "'I am ___' tells people how you feel inside."},
    {"lvl": 1, "scene": "🚽", "situ": "You need the bathroom.",
     "starters": ["I need", "I see", "Throw"],
     "ends": ["to go to the bathroom.", "a purple lion.", "the house."],
     "ok": [[0, 0]],
     "teach": "'I need ___' is for important things your body needs."},

    # ── Tier 2: help, ideas, feelings + because, joining in ──
    {"lvl": 2, "scene": "🎒", "situ": "Your backpack zipper is stuck.",
     "starters": ["I need help with", "It's time for", "I like to eat"],
     "ends": ["my zipper, please.", "a nap right now.", "pizza and juice."],
     "ok": [[0, 0]],
     "teach": "'I need help with ___' names the exact problem — helpers love that."},
    {"lvl": 2, "scene": "🎲", "situ": "You want to pick what to play next.",
     "starters": ["How about", "I lost", "It smells like"],
     "ends": ["we play a game?", "my other sock.", "rain today."],
     "ok": [[0, 0]],
     "teach": "'How about ___?' is a friendly way to share your idea."},
    {"lvl": 2, "scene": "🚪", "situ": "Your hands are full. The door is closed.",
     "starters": ["Can you", "I want", "It is"],
     "ends": ["open the door, please?", "more ketchup.", "raining outside."],
     "ok": [[0, 0]],
     "teach": "'Can you ___, please?' asks someone else to do a job."},
    {"lvl": 2, "scene": "🦷", "situ": "It is night time. Teeth time!",
     "starters": ["It's time to", "Can I have", "She is"],
     "ends": ["brush my teeth.", "a thousand cookies?", "riding a bike."],
     "ok": [[0, 0]],
     "teach": "'It's time to ___' tells what happens now in the routine."},
    {"lvl": 2, "scene": "🎢", "situ": "You rode a roller coaster!",
     "starters": ["I feel happy", "I feel sad", "I feel sleepy"],
     "ends": ["because that was so fun!", "because my ice cream fell.",
              "because it is very late."],
     "ok": [[0, 0]],
     "teach": "'I feel ___ because ___' tells the feeling AND the reason. Super sentence!"},
    {"lvl": 2, "scene": "🍦", "situ": "Your ice cream fell on the ground.",
     "starters": ["I feel sad", "I feel proud", "I feel silly"],
     "ends": ["because my ice cream fell.", "because I won the race.",
              "because I wore two hats."],
     "ok": [[0, 0]],
     "teach": "Match the feeling to the reason. Sad fits a fallen ice cream."},
    {"lvl": 2, "scene": "🧦", "situ": "One of your socks is missing.",
     "starters": ["Where is", "How many", "Why are"],
     "ends": ["my other sock?", "stars in the sky?", "bananas yellow?"],
     "ok": [[0, 0]],
     "teach": "'Where is ___?' finds lost things. WHERE asks about a place."},
    {"lvl": 2, "scene": "🚀", "situ": "The teacher asks what you will draw.",
     "starters": ["I'm going to", "I already", "Yesterday I"],
     "ends": ["draw a rocket.", "ate my lunch.", "went to the park."],
     "ok": [[0, 0]],
     "teach": "'I'm going to ___' tells what happens NEXT — the future!"},
    {"lvl": 2, "scene": "🧱", "situ": "Kids are building with blocks. You want to join.",
     "starters": ["Can I play", "Do you smell", "I am hiding"],
     "ends": ["with you?", "the flowers?", "under the bed."],
     "ok": [[0, 0]],
     "teach": "'Can I play with you?' is the magic key to joining a game."},
    {"lvl": 2, "scene": "🛒", "situ": "Someone is standing in your way at the store.",
     "starters": ["Excuse me,", "Happy birthday,", "Once upon a time,"],
     "ends": ["can I get through?", "dear dragon.", "there was a frog."],
     "ok": [[0, 0]],
     "teach": "'Excuse me' is the polite way to get someone's attention."},

    # ── Tier 3: because / but / so / first-then / opinions / repair ──
    {"lvl": 3, "scene": "☔", "situ": "It is raining hard. You want to play outside.",
     "starters": ["We can't play outside", "Let's swim outside", "The sun is loud"],
     "ends": ["because it is raining.", "because the grass is purple.",
              "because I said the magic word."],
     "ok": [[0, 0]],
     "teach": "'because' glues the WHAT to the WHY."},
    {"lvl": 3, "scene": "🍿", "situ": "It is movie night! What is the plan?",
     "starters": ["First we make popcorn,", "First we go to sleep,",
                  "First we wash the car,"],
     "ends": ["then we watch the movie.", "then we eat breakfast.",
              "then we brush the dog."],
     "ok": [[0, 0]],
     "teach": "'First ___, then ___' puts the plan in order. 1, then 2!"},
    {"lvl": 3, "scene": "🐘", "situ": "Which animal is the strongest? Say what YOU think.",
     "starters": ["I think the elephant is strongest",
                  "I think the mouse is loudest",
                  "I think the cheese is fastest"],
     "ends": ["because it is so big.", "because it squeaks at night.",
              "because it rolls downhill."],
     "ok": [[0, 0]],
     "teach": "'I think ___ because ___' shares your opinion WITH a reason."},
    {"lvl": 3, "scene": "🍰", "situ": "Grandma offers you more cake, but you are full.",
     "starters": ["No thank you,", "Yes please,", "Run away,"],
     "ends": ["I am full.", "I am empty.", "the cake is watching."],
     "ok": [[0, 0]],
     "teach": "'No thank you, I ___' says no AND why — polite and strong."},
    {"lvl": 3, "scene": "🌳", "situ": "You want to climb the tall tree, but it is not safe.",
     "starters": ["I want to climb it,", "I already climbed the sky,",
                  "The tree wants"],
     "ends": ["but it is not safe.", "but I am a ladder.", "a sandwich."],
     "ok": [[0, 0]],
     "teach": "'but' joins two ideas that pull in different directions."},
    {"lvl": 3, "scene": "🏠", "situ": "You are in the car, almost home. You are hungry.",
     "starters": ["When we get home,", "When the moon barks,",
                  "Before I was born,"],
     "ends": ["can I have a snack?", "I will be purple.", "the car ate lunch."],
     "ok": [[0, 0]],
     "teach": "'When ___, ___' connects a time to what happens at that time."},
    {"lvl": 3, "scene": "🧢", "situ": "You said 'cat' but you meant to say 'cap'.",
     "starters": ["Oops — I meant", "I am definitely", "Please pass"],
     "ends": ["the cap, not the cat.", "a helicopter.", "the Tuesday."],
     "ok": [[0, 0]],
     "teach": "'Oops — I meant ___' fixes a mix-up. Everyone mixes up words sometimes!"},
    {"lvl": 3, "scene": "🌧️🌈", "situ": "If the rain stops, what then?",
     "starters": ["If the rain stops,", "If my shoe sings,",
                  "If yesterday comes back,"],
     "ends": ["we can go outside.", "I will eat the song.",
              "we can un-eat lunch."],
     "ok": [[0, 0]],
     "teach": "'If ___, then ___' is a maybe-plan: it happens only if the first part happens."},
    {"lvl": 3, "scene": "🧸", "situ": "Your little brother is crying. His teddy bear is gone.",
     "starters": ["He is sad", "He is excited", "He is asleep"],
     "ends": ["because he lost his teddy.", "because he found ten teddies.",
              "because teddies are loud."],
     "ok": [[0, 0]],
     "teach": "You can use 'because' to explain OTHER people's feelings too."},
    {"lvl": 3, "scene": "😴", "situ": "You are very tired. So… what should happen?",
     "starters": ["I am tired,", "I am a pancake,", "My bed is hungry,"],
     "ends": ["so I will go to bed.", "so I will pour syrup on me.",
              "so it will eat my pillow."],
     "ok": [[0, 0]],
     "teach": "'so' tells what happens NEXT because of the first part."},
]

# ═══════════════════════ PICTURE MATCH ═══════════════════════
# Options are emoji-only on screen; labels are for speech + teach lines.

MATCH = [
    # ── Tier 1: who is doing what ──
    {"lvl": 1, "sent": "The dog is sleeping.",
     "opts": [("🐶💤", "a dog sleeping", 1),
              ("🐶🦴", "a dog with a bone", 0),
              ("🐱💤", "a cat sleeping", 0)],
     "teach": "Check WHO it is and WHAT they are doing. Dog + sleeping."},
    {"lvl": 1, "sent": "The girl is eating an apple.",
     "opts": [("👧🍎", "a girl with an apple", 1),
              ("👧🍦", "a girl with ice cream", 0),
              ("👦🍎", "a boy with an apple", 0)],
     "teach": "Girl + apple. Both parts have to match!"},
    {"lvl": 1, "sent": "Two birds are flying.",
     "opts": [("🐦🐦", "two birds", 1),
              ("🐦", "one bird", 0),
              ("🐦🐦🐦", "three birds", 0)],
     "teach": "TWO means exactly 2. Count them: 1, 2!"},
    {"lvl": 1, "sent": "The boy is kicking the ball.",
     "opts": [("👦⚽", "a boy with a ball", 1),
              ("👦📕", "a boy with a book", 0),
              ("👧⚽", "a girl with a ball", 0)],
     "teach": "Boy + ball. The sentence tells you both."},
    {"lvl": 1, "sent": "The cat is in the box.",
     "opts": [("🐱📦", "a cat with a box", 1),
              ("🐱🛏️", "a cat on a bed", 0),
              ("🐶📦", "a dog with a box", 0)],
     "teach": "Cat + box. Cats LOVE boxes!"},
    {"lvl": 1, "sent": "Grandpa is reading a book.",
     "opts": [("👴📖", "grandpa with a book", 1),
              ("👴☕", "grandpa with coffee", 0),
              ("👶📖", "a baby with a book", 0)],
     "teach": "Grandpa + book. WHO and WHAT both matter."},
    {"lvl": 1, "sent": "The fish is blue.",
     "opts": [("🐟💙", "a fish with blue", 1),
              ("🐟❤️", "a fish with red", 0),
              ("🐸💙", "a frog with blue", 0)],
     "teach": "Color words tell you which one. Blue fish!"},
    {"lvl": 1, "sent": "The baby is crying.",
     "opts": [("👶😢", "a crying baby", 1),
              ("👶😄", "a laughing baby", 0),
              ("👧😢", "a crying girl", 0)],
     "teach": "Baby + crying. The face shows the action."},
    {"lvl": 1, "sent": "Three apples are on the table.",
     "opts": [("🍎🍎🍎", "three apples", 1),
              ("🍎🍎", "two apples", 0),
              ("🍌🍌🍌", "three bananas", 0)],
     "teach": "Count first: 1, 2, 3. Then check it is apples!"},
    {"lvl": 1, "sent": "The rabbit is eating a carrot.",
     "opts": [("🐰🥕", "a rabbit with a carrot", 1),
              ("🐰🍎", "a rabbit with an apple", 0),
              ("🐿️🥕", "a squirrel with a carrot", 0)],
     "teach": "Rabbit + carrot. Match both parts."},
    {"lvl": 1, "sent": "It is raining.",
     "opts": [("🌧️☔", "rain and an umbrella", 1),
              ("☀️😎", "sun and sunglasses", 0),
              ("❄️⛄", "snow and a snowman", 0)],
     "teach": "Rain means water falling from clouds."},
    {"lvl": 1, "sent": "The boy is washing his hands.",
     "opts": [("🧒🧼", "a kid with soap", 1),
              ("🧒🍔", "a kid with a burger", 0),
              ("🧒⚽", "a kid with a ball", 0)],
     "teach": "Washing means soap and water."},

    # ── Tier 2: position words, NOT, he/she/they, more than one ──
    {"lvl": 2, "sent": "The ball is UNDER the chair.",
     "opts": [("🪑\n⚽", "a ball under a chair", 1),
              ("⚽\n🪑", "a ball on top of a chair", 0),
              ("⚽🪑", "a ball next to a chair", 0)],
     "teach": "UNDER means below — the chair is on top, the ball is at the bottom."},
    {"lvl": 2, "sent": "The bird is ON TOP of the house.",
     "opts": [("🐦\n🏠", "a bird on top of a house", 1),
              ("🏠\n🐦", "a bird under a house", 0),
              ("🐦🏠", "a bird next to a house", 0)],
     "teach": "ON TOP means up above — the bird sits on the roof."},
    {"lvl": 2, "sent": "The dog is NEXT TO the tree.",
     "opts": [("🐶🌳", "a dog beside a tree", 1),
              ("🌳\n🐶", "a dog under a tree", 0),
              ("🐱🌳", "a cat beside a tree", 0)],
     "teach": "NEXT TO means side by side."},
    {"lvl": 2, "sent": "Find the kid who is NOT eating.",
     "opts": [("🧒⚽", "a kid playing ball", 1),
              ("🧒🍕", "a kid eating pizza", 0),
              ("👧🍎", "a girl eating an apple", 0)],
     "teach": "NOT flips the meaning. Not eating = doing something else."},
    {"lvl": 2, "sent": "Find the animal that is NOT a pet.",
     "opts": [("🦁", "a lion", 1),
              ("🐶", "a dog", 0),
              ("🐱", "a cat", 0)],
     "teach": "Dogs and cats live with people. A lion is wild — NOT a pet!"},
    {"lvl": 2, "sent": "SHE is riding a bike.",
     "opts": [("👧🚲", "a girl on a bike", 1),
              ("👦🚲", "a boy on a bike", 0),
              ("👧📖", "a girl reading", 0)],
     "teach": "SHE means a girl or a woman."},
    {"lvl": 2, "sent": "HE is brushing his teeth.",
     "opts": [("👦🪥", "a boy with a toothbrush", 1),
              ("👧🪥", "a girl with a toothbrush", 0),
              ("👦🛁", "a boy in the bath", 0)],
     "teach": "HE means a boy or a man."},
    {"lvl": 2, "sent": "THEY are playing together.",
     "opts": [("👧👦⚽", "two kids with a ball", 1),
              ("👦⚽", "one boy with a ball", 0),
              ("👧📖", "one girl reading", 0)],
     "teach": "THEY means more than one person."},
    {"lvl": 2, "sent": "Find the cookies.",
     "opts": [("🍪🍪🍪", "three cookies", 1),
              ("🍪", "one cookie", 0),
              ("🧁🧁", "two cupcakes", 0)],
     "teach": "CookieS with an S means more than one cookie."},
    {"lvl": 2, "sent": "This is the GIRL'S hat.",
     "opts": [("👧🎩", "a girl with a hat", 1),
              ("👦🎩", "a boy with a hat", 0),
              ("👧👟", "a girl with a shoe", 0)],
     "teach": "The girl's hat = the hat belongs to the girl."},
    {"lvl": 2, "sent": "The dog is BETWEEN two trees.",
     "opts": [("🌳🐶🌳", "a dog in the middle of two trees", 1),
              ("🐶🌳🌳", "a dog beside two trees", 0),
              ("🌳🌳🐶", "two trees then a dog", 0)],
     "teach": "BETWEEN means in the middle — one on each side."},
    {"lvl": 2, "sent": "The star is ABOVE the house.",
     "opts": [("⭐\n🏠", "a star over a house", 1),
              ("🏠\n⭐", "a star under a house", 0),
              ("⭐🏠", "a star beside a house", 0)],
     "teach": "ABOVE means higher up, in the sky over the house."},

    # ── Tier 3: first/then, before/after, all/some, order, because ──
    {"lvl": 3, "sent": "First he eats dinner, then he brushes his teeth.",
     "opts": [("🍽️➡️🪥", "eating then brushing", 1),
              ("🪥➡️🍽️", "brushing then eating", 0),
              ("🍽️➡️🛁", "eating then a bath", 0)],
     "teach": "The arrow goes in time order: eating happens FIRST."},
    {"lvl": 3, "sent": "BEFORE she goes to bed, she reads a book.",
     "opts": [("📖➡️🛏️", "reading then bed", 1),
              ("🛏️➡️📖", "bed then reading", 0),
              ("📖➡️🍽️", "reading then eating", 0)],
     "teach": "BEFORE bed means the reading happens FIRST, bed comes after."},
    {"lvl": 3, "sent": "AFTER the rain, a rainbow came out.",
     "opts": [("🌧️➡️🌈", "rain then a rainbow", 1),
              ("🌈➡️🌧️", "a rainbow then rain", 0),
              ("🌧️➡️❄️", "rain then snow", 0)],
     "teach": "AFTER the rain means rain happened first, rainbow second."},
    {"lvl": 3, "sent": "The mouse is SMALLER than the dog. Find the smaller one.",
     "opts": [("🐭", "the mouse", 1),
              ("🐶", "the dog", 0),
              ("🐘", "the elephant", 0)],
     "teach": "SmallER compares two things — the mouse is the little one."},
    {"lvl": 3, "sent": "ALL the hearts are blue.",
     "opts": [("💙💙💙", "three blue hearts", 1),
              ("💙💙❤️", "two blue and one red", 0),
              ("❤️❤️❤️", "three red hearts", 0)],
     "teach": "ALL means every single one — no exceptions."},
    {"lvl": 3, "sent": "SOME of the hearts are blue.",
     "opts": [("💙💙❤️", "two blue hearts and one red", 1),
              ("💙💙💙", "all blue hearts", 0),
              ("❤️❤️❤️", "no blue hearts", 0)],
     "teach": "SOME means not all and not none — just a part."},
    {"lvl": 3, "sent": "The snowman is melting because the sun came out.",
     "opts": [("☀️⛄💧", "sun and a melting snowman", 1),
              ("❄️⛄", "snow and a happy snowman", 0),
              ("☀️🍦💧", "sun and melting ice cream", 0)],
     "teach": "BECAUSE links them: sun is the reason, melting is what happens."},
    {"lvl": 3, "sent": "He is wet because he jumped in the pool.",
     "opts": [("👦🏊💦", "a boy swimming with splashes", 1),
              ("👦🌂", "a dry boy with an umbrella", 0),
              ("👦🛏️", "a boy in bed", 0)],
     "teach": "Pool is the reason he is wet. Because = the reason."},
    {"lvl": 3, "sent": "The THIRD animal is a cat.",
     "opts": [("🐶🐰🐱", "dog, rabbit, cat", 1),
              ("🐱🐶🐰", "cat, dog, rabbit", 0),
              ("🐶🐱🐰", "dog, cat, rabbit", 0)],
     "teach": "Count from the left: 1, 2, 3. Third place = cat."},
    {"lvl": 3, "sent": "The SECOND fruit is a banana.",
     "opts": [("🍎🍌🍇", "apple, banana, grapes", 1),
              ("🍌🍎🍇", "banana, apple, grapes", 0),
              ("🍎🍇🍌", "apple, grapes, banana", 0)],
     "teach": "Second means position number 2. Count: 1, 2!"},
    {"lvl": 3, "sent": "She has a hat AND an umbrella.",
     "opts": [("👧🎩🌂", "a girl with a hat and an umbrella", 1),
              ("👧🎩", "a girl with only a hat", 0),
              ("👧🌂", "a girl with only an umbrella", 0)],
     "teach": "AND means both things — not just one."},
    {"lvl": 3, "sent": "He has a book but NO pencil.",
     "opts": [("👦📖", "a boy with only a book", 1),
              ("👦📖✏️", "a boy with a book and a pencil", 0),
              ("👦✏️", "a boy with only a pencil", 0)],
     "teach": "NO pencil means the pencil is missing. Book yes, pencil no."},
]

# ═══════════════════════ ROBO SAYS ═══════════════════════

DIRS = [
    # ── Tier 1: one step — color, shape, size, category ──
    {"lvl": 1, "instr": "Tap the red circle.",
     "items": [("🔴", "the red circle"), ("🔵", "the blue circle"),
               ("🟡", "the yellow circle")],
     "seq": [0],
     "teach": "Red is the color, circle is the shape. Both matched!"},
    {"lvl": 1, "instr": "Tap the blue square.",
     "items": [("🟦", "the blue square"), ("🔵", "the blue circle"),
               ("🟥", "the red square")],
     "seq": [0],
     "teach": "Two clues: BLUE and SQUARE. Only one has both."},
    {"lvl": 1, "instr": "Tap the star.",
     "items": [("⭐", "the star"), ("🌙", "the moon"), ("☀️", "the sun")],
     "seq": [0],
     "teach": "A star has 5 points!"},
    {"lvl": 1, "instr": "Tap the animal.",
     "items": [("🐮", "the cow"), ("🚗", "the car"), ("🍎", "the apple")],
     "seq": [0],
     "teach": "A cow is an animal. Cars and apples are things."},
    {"lvl": 1, "instr": "Tap the BIG heart.",
     "items": [("❤️", "the big heart", "big"), ("❤️", "the small heart", "small"),
               ("💛", "the yellow heart")],
     "seq": [0],
     "teach": "Same shape, different SIZE. Big means the large one."},
    {"lvl": 1, "instr": "Tap the food.",
     "items": [("🍌", "the banana"), ("⚽", "the ball"), ("📕", "the book")],
     "seq": [0],
     "teach": "Food is what we eat. You can eat a banana — not a ball!"},
    {"lvl": 1, "instr": "Tap the green circle.",
     "items": [("🟢", "the green circle"), ("🟩", "the green square"),
               ("🟡", "the yellow circle")],
     "seq": [0],
     "teach": "Green AND circle — you need both clues."},
    {"lvl": 1, "instr": "Tap the SMALL fish.",
     "items": [("🐟", "the big fish", "big"), ("🐟", "the small fish", "small"),
               ("🐳", "the whale")],
     "seq": [1],
     "teach": "Small means the little one. The whale is the biggest of all!"},
    {"lvl": 1, "instr": "Tap the thing that flies.",
     "items": [("✈️", "the airplane"), ("🚗", "the car"), ("⛵", "the boat")],
     "seq": [0],
     "teach": "Planes fly in the sky. Cars drive, boats float."},
    {"lvl": 1, "instr": "Tap the number five.",
     "items": [("5️⃣", "the number five"), ("2️⃣", "the number two"),
               ("9️⃣", "the number nine")],
     "seq": [0],
     "teach": "Five! Like 5 fingers on one hand."},

    # ── Tier 2: two steps — "X, then Y" ──
    {"lvl": 2, "instr": "Tap the cow, then tap the moon.",
     "items": [("🐮", "the cow"), ("🌙", "the moon"), ("⭐", "the star"),
               ("🚗", "the car")],
     "seq": [0, 1],
     "teach": "Two jobs in order: cow is number 1, moon is number 2."},
    {"lvl": 2, "instr": "Tap the apple, then tap the book.",
     "items": [("🍎", "the apple"), ("📕", "the book"), ("🐟", "the fish"),
               ("🎈", "the balloon")],
     "seq": [0, 1],
     "teach": "THEN means the second thing comes after the first."},
    {"lvl": 2, "instr": "Tap the sun, then tap the fish.",
     "items": [("☀️", "the sun"), ("🐟", "the fish"), ("🌙", "the moon"),
               ("🍦", "the ice cream")],
     "seq": [0, 1],
     "teach": "Sun first, fish second. 1, then 2."},
    {"lvl": 2, "instr": "First tap the drum, then tap the bell.",
     "items": [("🥁", "the drum"), ("🔔", "the bell"), ("🎸", "the guitar"),
               ("⚽", "the ball")],
     "seq": [0, 1],
     "teach": "FIRST and THEN tell you the order: drum 1, bell 2."},
    {"lvl": 2, "instr": "Tap the red heart, then the blue heart.",
     "items": [("❤️", "the red heart"), ("💙", "the blue heart"),
               ("💛", "the yellow heart"), ("💚", "the green heart")],
     "seq": [0, 1],
     "teach": "Red then blue — colors in order."},
    {"lvl": 2, "instr": "Tap the number 3, then the number 8.",
     "items": [("3️⃣", "the number three"), ("8️⃣", "the number eight"),
               ("5️⃣", "the number five"), ("1️⃣", "the number one")],
     "seq": [0, 1],
     "teach": "3 then 8. Fun fact: 3 + 8 = 11!"},
    {"lvl": 2, "instr": "Tap the dog, then tap the bone.",
     "items": [("🐶", "the dog"), ("🦴", "the bone"), ("🐱", "the cat"),
               ("🐟", "the fish")],
     "seq": [0, 1],
     "teach": "Dog first, bone second — now the dog is happy!"},
    {"lvl": 2, "instr": "First tap the train, then tap the airplane.",
     "items": [("🚂", "the train"), ("✈️", "the airplane"), ("🚗", "the car"),
               ("⛵", "the boat")],
     "seq": [0, 1],
     "teach": "Train on the ground first, then the plane in the sky."},
    {"lvl": 2, "instr": "Tap the cupcake, then tap the candle.",
     "items": [("🧁", "the cupcake"), ("🕯️", "the candle"), ("🎈", "the balloon"),
               ("🎁", "the present")],
     "seq": [0, 1],
     "teach": "Cupcake then candle — like getting ready for a birthday!"},
    {"lvl": 2, "instr": "Tap the smallest number, then the biggest number.",
     "items": [("2️⃣", "the number two"), ("7️⃣", "the number seven"),
               ("4️⃣", "the number four")],
     "seq": [0, 1],
     "teach": "2 is the smallest, 7 is the biggest. 2 < 4 < 7!"},

    # ── Tier 3: before/after, three steps, ordering, tricky words ──
    {"lvl": 3, "instr": "Before you tap the sun, tap the fish.",
     "items": [("☀️", "the sun"), ("🐟", "the fish"), ("🌙", "the moon")],
     "seq": [1, 0],
     "teach": "BEFORE flips the order! The fish comes first, sun second."},
    {"lvl": 3, "instr": "Tap the star after you tap the heart.",
     "items": [("⭐", "the star"), ("❤️", "the heart"), ("🌙", "the moon")],
     "seq": [1, 0],
     "teach": "AFTER the heart means: heart first, star second."},
    {"lvl": 3, "instr": "Tap the moon. But first, tap the cow.",
     "items": [("🌙", "the moon"), ("🐮", "the cow"), ("⭐", "the star")],
     "seq": [1, 0],
     "teach": "'But first' sneaks a job in FRONT: cow 1, moon 2."},
    {"lvl": 3, "instr": "Tap the apple, the ball, then the cat.",
     "items": [("🍎", "the apple"), ("⚽", "the ball"), ("🐱", "the cat"),
               ("🐟", "the fish")],
     "seq": [0, 1, 2],
     "teach": "Three steps! Apple 1, ball 2, cat 3."},
    {"lvl": 3, "instr": "Tap the biggest animal after you tap the smallest animal.",
     "items": [("🐘", "the elephant"), ("🐭", "the mouse"), ("🐶", "the dog")],
     "seq": [1, 0],
     "teach": "Smallest first (mouse), biggest after (elephant)."},
    {"lvl": 3, "instr": "Tap the numbers from smallest to biggest.",
     "items": [("6️⃣", "the number six"), ("2️⃣", "the number two"),
               ("9️⃣", "the number nine")],
     "seq": [1, 0, 2],
     "teach": "2, then 6, then 9 — counting up!"},
    {"lvl": 3, "instr": "Tap the numbers from biggest to smallest.",
     "items": [("3️⃣", "the number three"), ("8️⃣", "the number eight"),
               ("5️⃣", "the number five")],
     "seq": [1, 2, 0],
     "teach": "8, then 5, then 3 — counting down!"},
    {"lvl": 3, "instr": "Tap every heart, but NOT the star.",
     "items": [("❤️", "the red heart"), ("💙", "the blue heart"),
               ("⭐", "the star"), ("💛", "the yellow heart")],
     "seq": [0, 1, 3], "any": True,
     "teach": "EVERY heart means all 3 hearts. NOT the star means the star stays safe."},
    {"lvl": 3, "instr": "Before you tap the LAST animal, tap the FIRST animal.",
     "items": [("🐶", "the dog"), ("🐱", "the cat"), ("🐰", "the rabbit")],
     "seq": [0, 2], "fixed": True,
     "teach": "First = the dog at spot 1. Last = the rabbit at spot 3. Dog, then rabbit!"},
    {"lvl": 3, "instr": "Tap the fruit that is NOT red.",
     "items": [("🍎", "the apple"), ("🍌", "the banana"), ("🍓", "the strawberry")],
     "seq": [1],
     "teach": "Apple and strawberry are red. NOT red = the yellow banana."},
]

# ═══════════════════════ SAY IT ANOTHER WAY ═══════════════════════

SAME = [
    # ── Tier 1: same meaning, different words ──
    {"lvl": 1, "sent": "Dad is fixing the car.",
     "opts": [("Dad is repairing the car.", 1),
              ("Dad is washing the car.", 0),
              ("Dad is driving the car.", 0)],
     "teach": "Fixing and repairing are two words for the SAME job."},
    {"lvl": 1, "sent": "The baby is tired.",
     "opts": [("The baby wants to sleep.", 1),
              ("The baby wants to eat.", 0),
              ("The baby is playing.", 0)],
     "teach": "Tired means your body wants sleep."},
    {"lvl": 1, "sent": "Mia is happy.",
     "opts": [("Mia feels glad.", 1),
              ("Mia feels mad.", 0),
              ("Mia feels sleepy.", 0)],
     "teach": "Happy and glad are feeling-twins — same feeling, different word."},
    {"lvl": 1, "sent": "The backpack is heavy.",
     "opts": [("The backpack is hard to lift.", 1),
              ("The backpack is easy to carry.", 0),
              ("The backpack is brand new.", 0)],
     "teach": "Heavy means it weighs a lot, so lifting it is hard."},
    {"lvl": 1, "sent": "Tom shouted.",
     "opts": [("Tom talked very loudly.", 1),
              ("Tom whispered.", 0),
              ("Tom went to sleep.", 0)],
     "teach": "Shouting is talking with a BIG loud voice."},
    {"lvl": 1, "sent": "The room is messy.",
     "opts": [("Toys are all over the floor.", 1),
              ("The room is very clean.", 0),
              ("The room is dark.", 0)],
     "teach": "Messy means things are NOT where they belong."},
    {"lvl": 1, "sent": "The movie starts soon.",
     "opts": [("The movie starts in a little bit.", 1),
              ("The movie is already over.", 0),
              ("The movie started yesterday.", 0)],
     "teach": "Soon means a short time from now — not yet, but almost!"},
    {"lvl": 1, "sent": "Grandma is kind.",
     "opts": [("Grandma is nice to people.", 1),
              ("Grandma is very tall.", 0),
              ("Grandma is angry.", 0)],
     "teach": "Kind and nice mean the same thing."},
    {"lvl": 1, "sent": "The glass is empty.",
     "opts": [("There is nothing in the glass.", 1),
              ("The glass is full of milk.", 0),
              ("The glass is broken.", 0)],
     "teach": "Empty means zero inside. 0!"},
    {"lvl": 1, "sent": "Sam is quick.",
     "opts": [("Sam is fast.", 1),
              ("Sam is slow.", 0),
              ("Sam is loud.", 0)],
     "teach": "Quick and fast are the same speed!"},
    {"lvl": 1, "sent": "The puppy is little.",
     "opts": [("The puppy is small.", 1),
              ("The puppy is big.", 0),
              ("The puppy is wet.", 0)],
     "teach": "Little and small — two words, one size."},
    {"lvl": 1, "sent": "Dinner is ready.",
     "opts": [("It is time to eat.", 1),
              ("Dinner is all gone.", 0),
              ("It is time for bed.", 0)],
     "teach": "Ready means it is done cooking — time to eat!"},

    # ── Tier 2: everyday expressions people really say ──
    {"lvl": 2, "sent": "Hold on a second!",
     "opts": [("Please wait a moment.", 1),
              ("Hold something in your hand.", 0),
              ("Run as fast as you can.", 0)],
     "teach": "'Hold on' does not mean grab something — it means WAIT."},
    {"lvl": 2, "sent": "I'm full.",
     "opts": [("I don't want any more food.", 1),
              ("I am round like a ball.", 0),
              ("I want more food, please.", 0)],
     "teach": "'I'm full' means my tummy has enough food already."},
    {"lvl": 2, "sent": "It's time to hit the road.",
     "opts": [("It's time to leave.", 1),
              ("We should smack the street.", 0),
              ("It's time to eat lunch.", 0)],
     "teach": "'Hit the road' means GO — nobody actually hits anything!"},
    {"lvl": 2, "sent": "Can you give me a hand?",
     "opts": [("Can you help me?", 1),
              ("Please clap for me.", 0),
              ("Can you wave at me?", 0)],
     "teach": "'Give me a hand' means help me — your hands stay attached!"},
    {"lvl": 2, "sent": "I changed my mind.",
     "opts": [("I decided something different.", 1),
              ("I got a brand new brain.", 0),
              ("I forgot everything I knew.", 0)],
     "teach": "Changing your mind means picking a NEW choice. Brains stay put."},
    {"lvl": 2, "sent": "Keep an eye on your little sister.",
     "opts": [("Watch your sister.", 1),
              ("Put an eye on her head.", 0),
              ("Ignore your sister.", 0)],
     "teach": "'Keep an eye on' means watch carefully."},
    {"lvl": 2, "sent": "That cracks me up!",
     "opts": [("That is very funny!", 1),
              ("That is breaking my bones.", 0),
              ("That makes me very sad.", 0)],
     "teach": "'Cracks me up' means it makes me laugh a lot."},
    {"lvl": 2, "sent": "I'm all ears.",
     "opts": [("I am listening carefully.", 1),
              ("I am made of ears.", 0),
              ("I cannot hear anything.", 0)],
     "teach": "'All ears' means ready to listen — not covered in ears!"},
    {"lvl": 2, "sent": "Hang on tight!",
     "opts": [("Hold on very strongly.", 1),
              ("Hang from the ceiling.", 0),
              ("Let go right now.", 0)],
     "teach": "'Hang on tight' means grip hard and don't let go."},
    {"lvl": 2, "sent": "It slipped my mind.",
     "opts": [("I forgot about it.", 1),
              ("My brain fell on the floor.", 0),
              ("I remembered it perfectly.", 0)],
     "teach": "'Slipped my mind' means the thought slid away — I forgot."},
    {"lvl": 2, "sent": "We're out of milk.",
     "opts": [("There is no more milk.", 1),
              ("The milk went outside.", 0),
              ("We have lots of milk.", 0)],
     "teach": "'Out of' something means it is all gone — zero left."},
    {"lvl": 2, "sent": "Knock it off!",
     "opts": [("Please stop doing that.", 1),
              ("Knock on the door.", 0),
              ("Push it off the table.", 0)],
     "teach": "'Knock it off' means STOP — no knocking needed."},

    # ── Tier 3: idioms — every one has a literal trap ──
    {"lvl": 3, "sent": "It's raining cats and dogs.",
     "opts": [("It is raining very hard.", 1),
              ("Pets are falling from the sky.", 0),
              ("It just stopped raining.", 0)],
     "teach": "It's a SAYING. Sayings mean something different from the exact words. This one = super heavy rain."},
    {"lvl": 3, "sent": "This homework is a piece of cake.",
     "opts": [("This homework is very easy.", 1),
              ("The homework is a dessert.", 0),
              ("This homework is very hard.", 0)],
     "teach": "'A piece of cake' is a saying for EASY — easy like eating cake."},
    {"lvl": 3, "sent": "I have butterflies in my stomach.",
     "opts": [("I feel nervous.", 1),
              ("I ate some butterflies.", 0),
              ("I feel very hungry.", 0)],
     "teach": "A saying! Nervous tummies feel fluttery — like butterflies flying inside."},
    {"lvl": 3, "sent": "Break a leg!",
     "opts": [("Good luck!", 1),
              ("Please hurt your leg.", 0),
              ("Stop dancing right now.", 0)],
     "teach": "A saying actors use. 'Break a leg' means GOOD LUCK — no broken bones!"},
    {"lvl": 3, "sent": "Time to hit the hay.",
     "opts": [("Time to go to sleep.", 1),
              ("Time to punch some grass.", 0),
              ("Time to feed the horses.", 0)],
     "teach": "A saying! Long ago beds were made of hay — so 'hit the hay' = go to bed."},
    {"lvl": 3, "sent": "I'm feeling under the weather.",
     "opts": [("I feel a little sick.", 1),
              ("I am standing under a cloud.", 0),
              ("I feel super strong.", 0)],
     "teach": "'Under the weather' is a saying for feeling sick or blah."},
    {"lvl": 3, "sent": "That toy costs an arm and a leg.",
     "opts": [("That toy costs a lot of money.", 1),
              ("You pay for toys with your arm.", 0),
              ("That toy is free.", 0)],
     "teach": "A saying! 'An arm and a leg' means VERY expensive. You keep your arms."},
    {"lvl": 3, "sent": "Hold your horses!",
     "opts": [("Wait — don't go so fast!", 1),
              ("Grab a horse and hold it.", 0),
              ("Ride the horses right now.", 0)],
     "teach": "A saying! 'Hold your horses' means slow down and wait."},
    {"lvl": 3, "sent": "She has a heart of gold.",
     "opts": [("She is very kind.", 1),
              ("Her heart is made of metal.", 0),
              ("She is very rich.", 0)],
     "teach": "A saying! A 'heart of gold' means a super kind person."},
    {"lvl": 3, "sent": "The cat's out of the bag.",
     "opts": [("The secret is not a secret anymore.", 1),
              ("A cat escaped from a bag.", 0),
              ("It is time to feed the cat.", 0)],
     "teach": "A saying! When 'the cat's out of the bag', everyone knows the secret now."},
    {"lvl": 3, "sent": "We're in the same boat.",
     "opts": [("We have the same problem.", 1),
              ("We are sailing on the water.", 0),
              ("We should buy a boat.", 0)],
     "teach": "A saying! 'Same boat' means the same thing is happening to both of us."},
    {"lvl": 3, "sent": "It's on the tip of my tongue.",
     "opts": [("I almost remember the word.", 1),
              ("There is food on my tongue.", 0),
              ("I bit my tongue.", 0)],
     "teach": "A saying! The word feels SO close — you almost remember it."},
]

# ═══════════════════════ MIND MOVIES ═══════════════════════

STORIES = [
    # ── Tier 1: see it, find it, one clue ──
    {"lvl": 1, "title": "The Lost Shoe", "emoji": "👟",
     "text": "Ben has 2 shoes. He puts on 1 shoe, but he cannot find the "
             "other one. He looks under the bed. He looks behind the door. "
             "Then he sees it — the other shoe is in the dog's bed!",
     "qs": [
        {"q": "How many shoes does Ben have?",
         "opts": [("2", 1), ("1", 0), ("3", 0)],
         "teach": "The story starts: 'Ben has 2 shoes.'"},
        {"q": "Where was the missing shoe?",
         "opts": [("In the dog's bed", 1), ("Under the bed", 0),
                  ("Behind the door", 0)],
         "teach": "He looked in two places first — but it was in the dog's bed."},
        {"q": "Who do you think moved the shoe?",
         "opts": [("The dog", 1), ("Ben's mom", 0), ("Nobody", 0)],
         "teach": "The story doesn't SAY it — but the shoe was in the DOG'S bed. That's a clue!"},
     ]},
    {"lvl": 1, "title": "Pancake Morning", "emoji": "🥞",
     "text": "Mom makes 6 pancakes. Dad eats 2 pancakes. Ben eats 3 "
             "pancakes. One pancake is left on the plate. The cat looks at "
             "it and licks her lips.",
     "qs": [
        {"q": "How many pancakes did Mom make?",
         "opts": [("6", 1), ("5", 0), ("3", 0)],
         "teach": "The first sentence says 6. And 2 + 3 + 1 = 6. It checks out!"},
        {"q": "How many pancakes are left?",
         "opts": [("1", 1), ("2", 0), ("0", 0)],
         "teach": "6 − 2 − 3 = 1. One lonely pancake."},
        {"q": "What might happen next?",
         "opts": [("The cat may try to eat the pancake", 1),
                  ("The pancake will fly away", 0),
                  ("Dad will make a sandwich", 0)],
         "teach": "Licking lips is a clue: the cat WANTS that pancake!"},
     ]},
    {"lvl": 1, "title": "The Red Balloon", "emoji": "🎈",
     "text": "Zoe gets 1 red balloon at the fair. A strong wind starts to "
             "blow. Zoe holds the string with both hands. The wind stops. "
             "Zoe smiles.",
     "qs": [
        {"q": "What does Zoe hold?",
         "opts": [("The balloon string", 1), ("An ice cream", 0),
                  ("Her hat", 0)],
         "teach": "She holds the string — with BOTH hands."},
        {"q": "Why did Zoe hold on with both hands?",
         "opts": [("So the balloon would not fly away", 1),
                  ("Because her hands were cold", 0),
                  ("Because the balloon was heavy", 0)],
         "teach": "The wind was strong! Two hands kept the balloon safe."},
        {"q": "How does Zoe feel at the end?",
         "opts": [("Happy", 1), ("Angry", 0), ("Scared", 0)],
         "teach": "The story says she SMILED. A smile is a clue for happy."},
     ]},

    # ── Tier 2: why, prediction, feelings shift ──
    {"lvl": 2, "title": "The Wobbly Tooth", "emoji": "🦷",
     "text": "Sam has 20 teeth. One tooth is wobbly. He wiggles it 5 times "
             "at breakfast and 5 times at lunch. At dinner — POP! The tooth "
             "comes out. In the morning, Sam finds 1 dollar under his "
             "pillow.",
     "qs": [
        {"q": "How many times did Sam wiggle the tooth in all?",
         "opts": [("10", 1), ("5", 0), ("20", 0)],
         "teach": "5 at breakfast + 5 at lunch = 10 wiggles."},
        {"q": "What happened at dinner?",
         "opts": [("The tooth came out", 1),
                  ("Sam lost his dinner", 0),
                  ("Sam got a new tooth", 0)],
         "teach": "POP! That sound tells you the tooth came out."},
        {"q": "Why is there a dollar under the pillow?",
         "opts": [("The tooth fairy took the tooth and left money", 1),
                  ("Sam bought a dollar at dinner", 0),
                  ("The dollar fell out of his mouth", 0)],
         "teach": "The story never says 'tooth fairy' — but a tooth under a pillow turning into a dollar is her signature move!"},
     ]},
    {"lvl": 2, "title": "Rainy Recess", "emoji": "🌧️",
     "text": "It rains at recess, so the kids cannot go outside. They feel "
             "sad. Miss Lee brings out 4 board games. The 12 kids make 4 "
             "equal teams. Soon everyone is playing and laughing.",
     "qs": [
        {"q": "Why can't the kids go outside?",
         "opts": [("Because it is raining", 1),
                  ("Because it is too hot", 0),
                  ("Because recess is over", 0)],
         "teach": "'It rains at recess, SO they cannot go outside' — the rain is the reason."},
        {"q": "How many kids are on each team?",
         "opts": [("3", 1), ("4", 0), ("12", 0)],
         "teach": "12 kids ÷ 4 teams = 3 kids per team."},
        {"q": "The kids were sad at first. How do they feel at the end?",
         "opts": [("Happy", 1), ("Still sad", 0), ("Sleepy", 0)],
         "teach": "'Playing and LAUGHING' — laughing is a clue that the feeling changed to happy."},
     ]},
    {"lvl": 2, "title": "The Slow Turtle Wins", "emoji": "🐢",
     "text": "Rabbit and Turtle race to the big tree, 100 steps away. "
             "Rabbit runs 90 steps super fast, then stops to take a nap. "
             "Turtle walks and walks and never stops. Turtle passes the "
             "sleeping Rabbit and wins the race!",
     "qs": [
        {"q": "How long is the race?",
         "opts": [("100 steps", 1), ("90 steps", 0), ("10 steps", 0)],
         "teach": "The tree is 100 steps away. Rabbit stopped just 10 steps early — 90 + 10 = 100!"},
        {"q": "Why did Rabbit lose the race?",
         "opts": [("He stopped to sleep", 1),
                  ("He ran too fast the whole way", 0),
                  ("The tree moved away", 0)],
         "teach": "Rabbit was faster — but napping let Turtle walk right past him."},
        {"q": "What is the lesson of this story?",
         "opts": [("Keep going and don't give up", 1),
                  ("Naps always help you win", 0),
                  ("Never race a turtle", 0)],
         "teach": "Slow and steady wins the race — keep going, even if you are not the fastest."},
     ]},

    # ── Tier 3: clues, "how do you know", main idea ──
    {"lvl": 3, "title": "The Mystery Puddle", "emoji": "💧",
     "text": "Dad walks into the kitchen. There is a puddle of water on "
             "the floor. The freezer door is open a tiny bit. The ice cube "
             "tray is empty. Buddy the dog's chin is wet and dripping.",
     "qs": [
        {"q": "What do you think happened?",
         "opts": [("Buddy took ice cubes and they melted", 1),
                  ("Dad spilled his coffee", 0),
                  ("It rained inside the kitchen", 0)],
         "teach": "Nobody SAW it happen — but the clues point straight at Buddy!"},
        {"q": "How do you know? Pick the best clues.",
         "opts": [("Wet chin + empty tray + open freezer", 1),
                  ("The kitchen has a floor", 0),
                  ("Dogs like to sleep", 0)],
         "teach": "Detectives add up clues: 3 clues all point to one ice-stealing dog."},
        {"q": "What will Dad probably do next?",
         "opts": [("Close the freezer and wipe the floor", 1),
                  ("Go back to bed forever", 0),
                  ("Pour more water on the puddle", 0)],
         "teach": "Think what a grown-up does with a puddle and an open freezer — fix it!"},
     ]},
    {"lvl": 3, "title": "The Quiet Birthday", "emoji": "🎂",
     "text": "It is Aya's birthday. She opens the front door. The room is "
             "dark and very quiet. Then the lights flash on. 15 friends "
             "jump up and shout 'SURPRISE!' Aya's eyes get big and she "
             "laughs and laughs.",
     "qs": [
        {"q": "Why was the room dark and quiet at first?",
         "opts": [("Her friends were hiding for a surprise", 1),
                  ("The power was out", 0),
                  ("Everyone was asleep", 0)],
         "teach": "Dark + quiet + then SURPRISE = they were hiding on purpose!"},
        {"q": "How did Aya feel? How do you know?",
         "opts": [("Surprised and happy — big eyes and laughing", 1),
                  ("Angry — she slammed the door", 0),
                  ("Bored — she yawned", 0)],
         "teach": "Big eyes = surprised. Laughing = happy. Faces and actions are feeling-clues."},
        {"q": "Did Aya know about the party before she opened the door?",
         "opts": [("No — that is why it was a surprise", 1),
                  ("Yes, she planned the whole party", 0),
                  ("Yes, she bought the cake herself", 0)],
         "teach": "If she knew, it would not be a surprise. Her big eyes prove she did not know!"},
     ]},
    {"lvl": 3, "title": "The New Kid", "emoji": "🧒",
     "text": "A new kid named Leo stands alone at recess. He looks down at "
             "his shoes. He kicks a little rock. Mia walks over and says, "
             "'Want to play tag with us?' Leo looks up and smiles big.",
     "qs": [
        {"q": "How did Leo feel at the START? How do you know?",
         "opts": [("Lonely — he was alone, looking down", 1),
                  ("Excited — he was jumping around", 0),
                  ("Angry — he was shouting", 0)],
         "teach": "Standing alone + looking down + kicking a rock = lonely-clues."},
        {"q": "What did Mia do?",
         "opts": [("Invited Leo to play", 1),
                  ("Took Leo's rock", 0),
                  ("Told the teacher on Leo", 0)],
         "teach": "'Want to play tag with us?' is an invitation."},
        {"q": "What is this story MOSTLY about?",
         "opts": [("Being kind to someone new", 1),
                  ("How to play tag", 0),
                  ("Rocks on the playground", 0)],
         "teach": "Tag and rocks are small details. The BIG idea is Mia's kindness."},
     ]},
]

# ═══════════════════════ WHAT WOULD YOU SAY? ═══════════════════════

SAY = [
    # ── Tier 1: asking, telling, protesting — first power phrases ──
    {"lvl": 1, "scene": "🧃", "situ": "You want more juice.",
     "opts": [("More juice, please.", 1),
              ("Goodnight, everybody.", 0),
              ("The juice is orange.", 0)],
     "teach": "Asking with words works better than waiting and hoping!"},
    {"lvl": 1, "scene": "🔊", "situ": "The vacuum cleaner is too loud for your ears.",
     "opts": [("It's too loud. Can I take a break?", 1),
              ("I love this song.", 0),
              ("Vacuum, vacuum, vacuum.", 0)],
     "teach": "Telling people about your ears is a superpower. You can always ask for a break."},
    {"lvl": 1, "scene": "🤕", "situ": "You fell down and your knee hurts.",
     "opts": [("Ouch! My knee hurts. I need help.", 1),
              ("My shoes are blue.", 0),
              ("What's for dinner?", 0)],
     "teach": "Say WHERE it hurts and ask for help — grown-ups can fix it faster."},
    {"lvl": 1, "scene": "🎮", "situ": "Your sister is playing a game. You want a turn.",
     "opts": [("Can I have a turn, please?", 1),
              ("Mine! Mine! Mine!", 0),
              ("The TV is very big.", 0)],
     "teach": "'Can I have a turn?' gets you a turn. Grabbing gets you an argument."},
    {"lvl": 1, "scene": "🥦", "situ": "You do not want the broccoli on your plate.",
     "opts": [("No thank you. I don't like broccoli.", 1),
              ("I love broccoli so much!", 0),
              ("The fork is shiny.", 0)],
     "teach": "A kind NO: 'No thank you.' You never have to pretend to like it."},
    {"lvl": 1, "scene": "🚻", "situ": "You need the bathroom at school.",
     "opts": [("May I go to the bathroom?", 1),
              ("The bathroom is at my house.", 0),
              ("I like recess a lot.", 0)],
     "teach": "Body needs are always okay to say. Teachers want you to ask!"},
    {"lvl": 1, "scene": "👋", "situ": "A friend says 'Hi!' to you.",
     "opts": [("Hi! How are you?", 1),
              ("The end.", 0),
              ("My name is a secret.", 0)],
     "teach": "Saying hi back is like catching a ball and throwing it back."},
    {"lvl": 1, "scene": "🧩", "situ": "The puzzle piece will not fit, and you are stuck.",
     "opts": [("Can you help me, please?", 1),
              ("This puzzle has 100 pieces.", 0),
              ("Puzzles come from stores.", 0)],
     "teach": "Saying a FACT about the puzzle doesn't get help. ASKING gets help!"},
    {"lvl": 1, "scene": "🏫", "situ": "You miss your mom at school.",
     "opts": [("I miss my mom. Can I have a hug?", 1),
              ("Moms are tall.", 0),
              ("Where is the cafeteria?", 0)],
     "teach": "Naming the feeling AND asking for what helps — that's a double win."},
    {"lvl": 1, "scene": "🛑", "situ": "A kid is standing too close and it bothers you.",
     "opts": [("Please step back. I need some space.", 1),
              ("You are a giraffe.", 0),
              ("I am invisible now.", 0)],
     "teach": "Asking for space with words is strong and kind at the same time."},

    # ── Tier 2: repair, joining, politeness, honesty ──
    {"lvl": 2, "scene": "👂", "situ": "Grandma said something, but you did not hear it.",
     "opts": [("Can you say that again, please?", 1),
              ("Okay.", 0),
              ("Goodbye, Grandma.", 0)],
     "teach": "Saying 'okay' when you didn't hear causes mix-ups. Asking again fixes everything."},
    {"lvl": 2, "scene": "🗣️", "situ": "Two grown-ups are talking. You need to tell Mom something.",
     "opts": [("Excuse me, Mom…", 1),
              ("MOM MOM MOM MOM MOM.", 0),
              ("The floor is quiet.", 0)],
     "teach": "'Excuse me' is the door-knock of talking — then wait a moment."},
    {"lvl": 2, "scene": "😞", "situ": "Your friend is sitting alone and looks sad.",
     "opts": [("Are you okay?", 1),
              ("Sad is a feeling.", 0),
              ("Watch me run super fast!", 0)],
     "teach": "'Are you okay?' shows you care. It's a tiny question with big power."},
    {"lvl": 2, "scene": "💥", "situ": "You bumped into someone by accident.",
     "opts": [("I'm sorry! Are you okay?", 1),
              ("It wasn't me.", 0),
              ("People bump sometimes.", 0)],
     "teach": "Accident + sorry = fixed fast. No sorry = the problem grows."},
    {"lvl": 2, "scene": "🏗️", "situ": "Kids are building a big tower. You want to join.",
     "opts": [("That's so cool! Can I build too?", 1),
              ("I have better blocks at home.", 0),
              ("Towers always fall down.", 0)],
     "teach": "To join a game: say something NICE about it, then ASK."},
    {"lvl": 2, "scene": "❓", "situ": "The teacher explains something, but you don't understand.",
     "opts": [("I don't get it. Can you show me?", 1),
              ("I know everything already.", 0),
              ("My pencil is yellow.", 0)],
     "teach": "Not understanding is normal. Asking is what smart, brave people do."},
    {"lvl": 2, "scene": "🍿", "situ": "Your friend shares their snack with you.",
     "opts": [("Thank you! That's so nice.", 1),
              ("I have better snacks at home.", 0),
              ("Snacks are food.", 0)],
     "teach": "'Thank you' makes people want to share again."},
    {"lvl": 2, "scene": "🏆", "situ": "You won the game. Your friend lost.",
     "opts": [("Good game! Want to play again?", 1),
              ("I always win! I'm the best!", 0),
              ("Losing is bad.", 0)],
     "teach": "Kind winners get invited back. Bragging feels bad for the loser."},
    {"lvl": 2, "scene": "📞", "situ": "You answer the phone. The call is for Dad.",
     "opts": [("Just a minute, please — I'll go get him.", 1),
              ("Dad is in the bathroom right now.", 0),
              ("Bye.", 0)],
     "teach": "Short and helpful — and nobody needs bathroom details!"},
    {"lvl": 2, "scene": "🍽️", "situ": "At a restaurant, you want some water.",
     "opts": [("Can I have some water, please?", 1),
              ("Water! Water! Water!", 0),
              ("Restaurants have kitchens.", 0)],
     "teach": "The asking frame works everywhere — home, school, restaurants."},

    # ── Tier 3: perspective, flexibility, kind honesty, safety ──
    {"lvl": 3, "scene": "🏰", "situ": "Your friend's block tower falls down. He looks upset.",
     "opts": [("Oh no! Want help building it again?", 1),
              ("Your tower was too tall. That's why it fell.", 0),
              ("My tower never falls.", 0)],
     "teach": "Saying WHY it fell is true — but feelings come first. Check the feeling, then help."},
    {"lvl": 3, "scene": "🎁", "situ": "Grandma gives you a gift you do not really like.",
     "opts": [("Thank you, Grandma.", 1),
              ("I don't want this. Take it back.", 0),
              ("This is the worst gift ever.", 0)],
     "teach": "'Thank you' protects Grandma's heart. You can tell Mom your true feelings later, in private."},
    {"lvl": 3, "scene": "⚽🚂", "situ": "Your friend wants to talk about soccer. You love trains.",
     "opts": [("Sure — soccer first, then can I tell you about trains?", 1),
              ("Trains. Trains. Trains. Trains.", 0),
              ("Soccer is boring.", 0)],
     "teach": "Topics work like turns in a game: their topic, then your topic."},
    {"lvl": 3, "scene": "🌧️🦁", "situ": "The zoo trip is cancelled because of rain. The plan changed!",
     "opts": [("Aww. Okay — what can we do instead?", 1),
              ("NO! We are going anyway!", 0),
              ("Rain ruins everything forever.", 0)],
     "teach": "'What can we do instead?' is a flexible-brain phrase. Plans bend — you can too."},
    {"lvl": 3, "scene": "😠", "situ": "A kid keeps teasing you at recess.",
     "opts": [("Stop. I don't like that.", 1),
              ("You're even more stupid.", 0),
              ("I will just say nothing every time.", 0)],
     "teach": "Strong words first: 'Stop. I don't like that.' If it keeps happening, tell a grown-up — that is not tattling, that is smart."},
    {"lvl": 3, "scene": "❌", "situ": "You gave a wrong answer in class, and other kids heard.",
     "opts": [("Oops — let me try again.", 1),
              ("I'm so dumb.", 0),
              ("The question was broken.", 0)],
     "teach": "Talk to yourself like a coach, not a bully. Mistakes are your brain growing."},
    {"lvl": 3, "scene": "🆕", "situ": "A new kid is standing alone at recess.",
     "opts": [("Hi! Want to play with us?", 1),
              ("You're new. New kids have to wait.", 0),
              ("I was here first.", 0)],
     "teach": "Remember Leo? One invitation can fix a whole lonely day."},
    {"lvl": 3, "scene": "💔", "situ": "You broke your brother's toy by accident.",
     "opts": [("I'm sorry. It was an accident. Can I help fix it?", 1),
              ("What toy? I never saw a toy.", 0),
              ("Toys break. Get over it.", 0)],
     "teach": "Sorry + it was an accident + offer to help = the full repair kit."},
    {"lvl": 3, "scene": "🤫", "situ": "Your friend tells you a fun secret: a surprise party for Mom.",
     "opts": [("Got it — my lips are zipped until the party!", 1),
              ("MOM! There's a surprise party for you!", 0),
              ("Secrets are illegal.", 0)],
     "teach": "Fun surprise secrets: keep until the day. But a secret that feels scary or bad? ALWAYS tell a trusted grown-up."},
    {"lvl": 3, "scene": "🐌", "situ": "Grandpa walks slowly. You want to run ahead at the park.",
     "opts": [("Grandpa, I'll run to that bench and wait for you there!", 1),
              ("Hurry UP! You're too slow!", 0),
              ("Bye!", 0)],
     "teach": "A plan-sentence keeps everyone safe AND lets you run. Win-win!"},
]
