"""
wh_data.py — question bank for WH Question Quest (autism/wh-quest.md).

Consumed by _tools/build-wh-quest.py, which packs it as JSON and encrypts it
into the page front matter. The game engine lives in
_layouts/protected-wh.html — editing games there never requires re-encryption;
editing THIS file does (re-run build-wh-quest.py).

Schema
------
QUESTIONS: list of dicts
    wh    : "who" | "what" | "where" | "why" | "how"
    lvl   : 1 (cross-category foils — wrong answers are a different WH
              category, which teaches the mapping "who = person" etc.)
            2 (same-category foils — real comprehension required)
    scene : emoji string shown big above the question
    q     : the question text (WH word must be the first word)
    opts  : list of (emoji, text, correct) — exactly one correct=1
    teach : optional extra teaching line shown after answering
            (engine always shows the generic one, e.g. "WHO asks about a
            person." — this adds a question-specific line after it)

STORIES: list of dicts
    title : story name
    emoji : cover emoji
    text  : 2–5 short sentences, number-rich
    qs    : list of question dicts (same shape as QUESTIONS, scene optional)

STATES: list of (state, capital) — all 50 US states, alphabetical.
"""

QUESTIONS = [
    # ════════════════════════ WHO ════════════════════════
    # level 1 (foils are things/places)
    {"wh": "who", "lvl": 1, "scene": "🔥🚒",
     "q": "Who puts out the fire?",
     "opts": [("🧑‍🚒", "the firefighter", 1), ("🚗", "a car", 0),
              ("🍎", "an apple", 0)],
     "teach": "The firefighter is a person!"},
    {"wh": "who", "lvl": 1, "scene": "🏫📚",
     "q": "Who teaches kids at school?",
     "opts": [("🛏️", "a bed", 0), ("👩‍🏫", "the teacher", 1),
              ("🍌", "a banana", 0)],
     "teach": "The teacher is a person!"},
    {"wh": "who", "lvl": 1, "scene": "🤒🏥",
     "q": "Who helps you when you are sick?",
     "opts": [("🧦", "a sock", 0), ("🌳", "a tree", 0),
              ("🧑‍⚕️", "the doctor", 1)],
     "teach": "The doctor is a person!"},
    {"wh": "who", "lvl": 1, "scene": "🍳🍲",
     "q": "Who cooks food at a restaurant?",
     "opts": [("👨‍🍳", "the chef", 1), ("🚲", "a bike", 0),
              ("🏖️", "the beach", 0)],
     "teach": "The chef is a person!"},
    {"wh": "who", "lvl": 1, "scene": "🚌🛣️",
     "q": "Who drives the bus?",
     "opts": [("🍕", "a pizza", 0), ("🧑‍✈️", "the driver", 1),
              ("🌧️", "the rain", 0)],
     "teach": "The driver is a person!"},
    {"wh": "who", "lvl": 1, "scene": "👶🍼",
     "q": "Who drinks from a bottle?",
     "opts": [("👶", "the baby", 1), ("📕", "a book", 0),
              ("🏫", "the school", 0)],
     "teach": "The baby is a person!"},
    {"wh": "who", "lvl": 1, "scene": "💇✂️",
     "q": "Who cuts your hair?",
     "opts": [("💇‍♀️", "the hairdresser", 1), ("🥦", "a broccoli", 0),
              ("🚂", "a train", 0)]},
    {"wh": "who", "lvl": 1, "scene": "🎤🎵",
     "q": "Who sings the song?",
     "opts": [("🧱", "a brick", 0), ("👩‍🎤", "the singer", 1),
              ("🌧️", "the rain", 0)]},
    {"wh": "who", "lvl": 1, "scene": "🎨🖼️",
     "q": "Who paints the picture?",
     "opts": [("🧑‍🎨", "the artist", 1), ("🍩", "a donut", 0),
              ("🏔️", "a mountain", 0)]},
    {"wh": "who", "lvl": 1, "scene": "🚓🚨",
     "q": "Who catches the robbers?",
     "opts": [("🍦", "an ice cream", 0), ("👮", "the police officer", 1),
              ("🌉", "a bridge", 0)]},
    {"wh": "who", "lvl": 1, "scene": "🚗🔧",
     "q": "Who fixes the broken car?",
     "opts": [("🧑‍🔧", "the mechanic", 1), ("🎈", "a balloon", 0),
              ("🏝️", "an island", 0)]},
    {"wh": "who", "lvl": 1, "scene": "🍕🛵",
     "q": "Who brings the pizza to your house?",
     "opts": [("🪨", "a rock", 0), ("🛵", "the delivery driver", 1),
              ("🌛", "the moon", 0)]},

    # level 2 (foils are also people)
    {"wh": "who", "lvl": 2, "scene": "✈️☁️",
     "q": "Who flies the airplane?",
     "opts": [("🧑‍✈️", "the pilot", 1), ("👨‍🍳", "the chef", 0),
              ("🧑‍🌾", "the farmer", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🐄🌾🚜",
     "q": "Who grows food on a farm?",
     "opts": [("👮", "the police officer", 0), ("🧑‍🌾", "the farmer", 1),
              ("🧑‍🚀", "the astronaut", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🚀🌕",
     "q": "Who flies to space?",
     "opts": [("🧑‍🚀", "the astronaut", 1), ("👩‍🏫", "the teacher", 0),
              ("🦷🧑‍⚕️", "the dentist", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🦷✨",
     "q": "Who checks your teeth?",
     "opts": [("🧑‍🚒", "the firefighter", 0), ("🧑‍⚕️", "the dentist", 1),
              ("🧑‍✈️", "the pilot", 0)]},
    {"wh": "who", "lvl": 2, "scene": "👑🏰",
     "q": "Who wears a crown?",
     "opts": [("🤴", "the king", 1), ("👨‍🍳", "the chef", 0),
              ("👮", "the police officer", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🎂🕯️",
     "q": "Who blows out the candles at a birthday party?",
     "opts": [("👩‍🏫", "the teacher", 0), ("🧒", "the birthday kid", 1),
              ("👮", "the police officer", 0)]},
    {"wh": "who", "lvl": 2, "scene": "📚🤫",
     "q": "Who helps you find books at the library?",
     "opts": [("📚🧑", "the librarian", 1), ("👨‍🍳", "the chef", 0),
              ("🧑‍✈️", "the pilot", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🍞🎂",
     "q": "Who bakes bread and cakes?",
     "opts": [("🧑‍⚕️", "the doctor", 0), ("🧑‍🍳", "the baker", 1),
              ("👮", "the police officer", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🚂🛤️",
     "q": "Who drives the train?",
     "opts": [("🧑‍✈️", "the train driver", 1), ("👨‍🍳", "the chef", 0),
              ("🧑‍🎨", "the artist", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🎸🥁",
     "q": "Who plays music in a band?",
     "opts": [("🧑‍🌾", "the farmer", 0), ("🧑‍🎤", "the musician", 1),
              ("🧑‍⚕️", "the doctor", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🔭✨",
     "q": "Who studies the stars at night?",
     "opts": [("🧑‍🔬", "the scientist", 1), ("👨‍🍳", "the chef", 0),
              ("💇‍♀️", "the hairdresser", 0)]},
    {"wh": "who", "lvl": 2, "scene": "✉️📬",
     "q": "Who delivers letters to your mailbox?",
     "opts": [("🧑‍🚀", "the astronaut", 0), ("📬🧑", "the mail carrier", 1),
              ("👨‍🍳", "the chef", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🏊🛟",
     "q": "Who keeps you safe at the pool?",
     "opts": [("🛟🧑", "the lifeguard", 1), ("🧑‍🎨", "the artist", 0),
              ("🤴", "the king", 0)]},
    {"wh": "who", "lvl": 2, "scene": "👵💐",
     "q": "Who is your mom's mom?",
     "opts": [("👶", "the baby", 0), ("👵", "your grandma", 1),
              ("👨‍🍳", "the chef", 0)]},
    {"wh": "who", "lvl": 2, "scene": "🐶🏥🐾",
     "q": "Who takes care of sick animals?",
     "opts": [("🐾🧑‍⚕️", "the vet", 1), ("🧑‍✈️", "the pilot", 0),
              ("🧑‍🎤", "the singer", 0)]},
    {"wh": "who", "lvl": 2, "scene": "⚽🥅",
     "q": "Who kicks the ball into the goal?",
     "opts": [("🧑‍🔬", "the scientist", 0), ("⚽🏃", "the soccer player", 1),
              ("📬🧑", "the mail carrier", 0)]},

    # ════════════════════════ WHAT ════════════════════════
    # level 1
    {"wh": "what", "lvl": 1, "scene": "😴🌙",
     "q": "What do you sleep in?",
     "opts": [("🛏️", "a bed", 1), ("👩‍🏫", "the teacher", 0),
              ("🏊", "swimming", 0)],
     "teach": "A bed is a thing!"},
    {"wh": "what", "lvl": 1, "scene": "📄✂️",
     "q": "What cuts paper?",
     "opts": [("👵", "grandma", 0), ("✂️", "scissors", 1),
              ("🏫", "the school", 0)],
     "teach": "Scissors are a thing!"},
    {"wh": "what", "lvl": 1, "scene": "🕐⏰",
     "q": "What tells you the time?",
     "opts": [("🕐", "a clock", 1), ("🧑‍🚒", "the firefighter", 0),
              ("🌊", "the sea", 0)],
     "teach": "A clock is a thing!"},
    {"wh": "what", "lvl": 1, "scene": "🦷🪥",
     "q": "What do you brush your teeth with?",
     "opts": [("👟", "a shoe", 0), ("🪥", "a toothbrush", 1),
              ("🐶", "a dog", 0)]},
    {"wh": "what", "lvl": 1, "scene": "🌧️💧",
     "q": "What keeps you dry in the rain?",
     "opts": [("☂️", "an umbrella", 1), ("🍦", "an ice cream", 0),
              ("📺", "a TV", 0)]},
    {"wh": "what", "lvl": 1, "scene": "🥛🧃",
     "q": "What do you drink from?",
     "opts": [("🥤", "a cup", 1), ("👟", "a shoe", 0),
              ("🧑‍🚒", "the firefighter", 0)]},
    {"wh": "what", "lvl": 1, "scene": "☀️🧢",
     "q": "What do you wear on your head?",
     "opts": [("🏫", "the school", 0), ("🧢", "a hat", 1),
              ("🐟", "a fish", 0)]},
    {"wh": "what", "lvl": 1, "scene": "🌙✨",
     "q": "What shines in the sky at night?",
     "opts": [("🌙", "the moon", 1), ("🥄", "a spoon", 0),
              ("🧑‍⚕️", "the doctor", 0)]},
    {"wh": "what", "lvl": 1, "scene": "📝✏️",
     "q": "What do you write with?",
     "opts": [("🍔", "a burger", 0), ("✏️", "a pencil", 1),
              ("🏖️", "the beach", 0)]},
    {"wh": "what", "lvl": 1, "scene": "🚲💨",
     "q": "What has two wheels and pedals?",
     "opts": [("🚲", "a bike", 1), ("👵", "grandma", 0),
              ("🌧️", "the rain", 0)]},
    {"wh": "what", "lvl": 1, "scene": "⚽🙌",
     "q": "What do you bounce and kick?",
     "opts": [("🌳", "a tree", 0), ("⚽", "a ball", 1),
              ("👩‍🏫", "the teacher", 0)]},
    {"wh": "what", "lvl": 1, "scene": "🥶🧤",
     "q": "What keeps your hands warm?",
     "opts": [("🧤", "mittens", 1), ("🍕", "a pizza", 0),
              ("🏊", "swimming", 0)]},

    # level 2
    {"wh": "what", "lvl": 2, "scene": "👦🍕",
     "q": "What is the boy eating?",
     "opts": [("🍕", "pizza", 1), ("🍎", "an apple", 0),
              ("🍪", "a cookie", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🐱💤",
     "q": "What is the cat doing?",
     "opts": [("💤", "sleeping", 1), ("🍽️", "eating", 0),
              ("🏃", "running", 0)],
     "teach": "WHAT can also ask about an action — what someone is DOING."},
    {"wh": "what", "lvl": 2, "scene": "👧🎨🖌️",
     "q": "What is the girl doing?",
     "opts": [("🎨", "painting", 1), ("💤", "sleeping", 0),
              ("🍽️", "eating", 0)]},
    {"wh": "what", "lvl": 2, "scene": "👶😭",
     "q": "What is the baby doing?",
     "opts": [("😂", "laughing", 0), ("😭", "crying", 1),
              ("🏊", "swimming", 0)]},
    {"wh": "what", "lvl": 2, "scene": "👨🍳🍳",
     "q": "What is Dad doing in the kitchen?",
     "opts": [("🍳", "cooking", 1), ("🚗", "driving", 0),
              ("📖", "reading", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🍝🍴",
     "q": "What do you use to eat spaghetti?",
     "opts": [("🍴", "a fork", 1), ("🥤", "a straw", 0),
              ("🪥", "a toothbrush", 0)]},
    {"wh": "what", "lvl": 2, "scene": "☀️🍦",
     "q": "What melts in the hot sun?",
     "opts": [("🪨", "a rock", 0), ("🍦", "ice cream", 1),
              ("🥄", "a spoon", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🌱🌻",
     "q": "What grows from a little seed?",
     "opts": [("🌻", "a flower", 1), ("🧸", "a teddy bear", 0),
              ("🪨", "a rock", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🐝🌼",
     "q": "What do bees make?",
     "opts": [("🥛", "milk", 0), ("🍯", "honey", 1),
              ("🍞", "bread", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🐄🌾",
     "q": "What do cows give us?",
     "opts": [("🥛", "milk", 1), ("🍯", "honey", 0),
              ("🍟", "french fries", 0)]},
    {"wh": "what", "lvl": 2, "scene": "👦🧱🏰",
     "q": "What is the boy building with blocks?",
     "opts": [("🏰", "a castle", 1), ("🎂", "a cake", 0),
              ("🧦", "a sock", 0)]},
    {"wh": "what", "lvl": 2, "scene": "🔺",
     "q": "What shape has 3 sides?",
     "opts": [("⬜", "a square", 0), ("🔺", "a triangle", 1),
              ("⚪", "a circle", 0)],
     "teach": "Tri- means 3. Tri-angle = 3 angles!"},
    {"wh": "what", "lvl": 2, "scene": "⬜",
     "q": "What shape has 4 equal sides?",
     "opts": [("🔺", "a triangle", 0), ("⚪", "a circle", 0),
              ("⬜", "a square", 1)]},
    {"wh": "what", "lvl": 2, "scene": "🛑",
     "q": "What shape has 8 sides, like a stop sign?",
     "opts": [("🛑", "an octagon", 1), ("🔺", "a triangle", 0),
              ("⬜", "a square", 0)],
     "teach": "Oct- means 8. An octopus has 8 arms, an octagon has 8 sides!"},
    {"wh": "what", "lvl": 2, "scene": "⚽🌍",
     "q": "What shape is a ball?",
     "opts": [("🎲", "a cube", 0), ("⚪", "a sphere", 1),
              ("🔺", "a triangle", 0)],
     "teach": "A ball is a sphere — a round shape you can hold!"},
    {"wh": "what", "lvl": 2, "scene": "9️⃣➡️❓",
     "q": "What number comes after 9?",
     "opts": [("🔟", "10", 1), ("8️⃣", "8", 0), ("7️⃣", "7", 0)]},
    {"wh": "what", "lvl": 2, "scene": "💯➖1️⃣",
     "q": "What number is one less than 100?",
     "opts": [("9️⃣9️⃣", "99", 1), ("9️⃣0️⃣", "90", 0),
              ("1️⃣0️⃣1️⃣", "101", 0)]},
    {"wh": "what", "lvl": 2, "scene": "6️⃣✖️2️⃣",
     "q": "What number do you get when you double 6?",
     "opts": [("1️⃣2️⃣", "12", 1), ("8️⃣", "8", 0), ("3️⃣6️⃣", "36", 0)],
     "teach": "Double means times 2: 6 × 2 = 12."},
    {"wh": "what", "lvl": 2, "scene": "2️⃣✖️5️⃣",
     "q": "What is 2 times 5?",
     "opts": [("🔟", "10", 1), ("7️⃣", "7", 0), ("2️⃣5️⃣", "25", 0)]},

    # ════════════════════════ WHERE ════════════════════════
    # level 1
    {"wh": "where", "lvl": 1, "scene": "🐟💭",
     "q": "Where do fish live?",
     "opts": [("🌊", "in the water", 1), ("🧑‍⚕️", "the doctor", 0),
              ("✂️", "scissors", 0)],
     "teach": "In the water is a place!"},
    {"wh": "where", "lvl": 1, "scene": "📚✏️🎒",
     "q": "Where do you go to learn?",
     "opts": [("🍎", "an apple", 0), ("🏫", "to school", 1),
              ("👶", "the baby", 0)],
     "teach": "School is a place!"},
    {"wh": "where", "lvl": 1, "scene": "🐦🥚",
     "q": "Where does a bird build its nest?",
     "opts": [("🌳", "in a tree", 1), ("🪥", "a toothbrush", 0),
              ("👨‍🍳", "the chef", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🛒🥕🍞",
     "q": "Where do you buy food?",
     "opts": [("🕐", "a clock", 0), ("🏪", "at the store", 1),
              ("☂️", "an umbrella", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🚗🚙🚕",
     "q": "Where do cars drive?",
     "opts": [("🛣️", "on the road", 1), ("👵", "grandma", 0),
              ("🥄", "a spoon", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🛁🫧",
     "q": "Where do you take a bath?",
     "opts": [("🍩", "a donut", 0), ("🛁", "in the bathroom", 1),
              ("👮", "the police officer", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🍳🥘",
     "q": "Where do you cook dinner?",
     "opts": [("🍳", "in the kitchen", 1), ("⚽", "a ball", 0),
              ("👶", "the baby", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🦁🐘🦓",
     "q": "Where do you go to see lions and elephants?",
     "opts": [("🧦", "a sock", 0), ("🦓", "at the zoo", 1),
              ("🍦", "an ice cream", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🌻🌷",
     "q": "Where do you plant flowers?",
     "opts": [("🌱", "in the garden", 1), ("📺", "a TV", 0),
              ("🧑‍✈️", "the pilot", 0)]},
    {"wh": "where", "lvl": 1, "scene": "✈️🛬",
     "q": "Where do airplanes land?",
     "opts": [("🍪", "a cookie", 0), ("🛬", "at the airport", 1),
              ("🐟", "a fish", 0)]},
    {"wh": "where", "lvl": 1, "scene": "📚🤫",
     "q": "Where do you borrow books?",
     "opts": [("📚", "at the library", 1), ("🪥", "a toothbrush", 0),
              ("👵", "grandma", 0)]},
    {"wh": "where", "lvl": 1, "scene": "🤕🚑",
     "q": "Where do you go when you are very sick?",
     "opts": [("🎈", "a balloon", 0), ("🏥", "to the hospital", 1),
              ("🌙", "the moon", 0)]},

    # level 2
    {"wh": "where", "lvl": 2, "scene": "🐱⬆️🛏️",
     "q": "Where is the cat?",
     "opts": [("🛏️", "on the bed", 1), ("🚗", "in the car", 0),
              ("🏫", "at school", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🚀🌌",
     "q": "Where does the rocket go?",
     "opts": [("🌊", "under the sea", 0), ("🌕", "to the moon", 1),
              ("🏪", "to the store", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🏊💦",
     "q": "Where do you swim?",
     "opts": [("🛏️", "in bed", 0), ("🏊", "in the pool", 1),
              ("🛣️", "on the road", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🐶🦴⬇️🪑",
     "q": "Where is the dog hiding the bone?",
     "opts": [("🪑", "under the chair", 1), ("☁️", "in the sky", 0),
              ("🎒", "in the backpack", 0)]},
    {"wh": "where", "lvl": 2, "scene": "👟🦶",
     "q": "Where do your shoes go?",
     "opts": [("🖐️", "on your hands", 0), ("🦶", "on your feet", 1),
              ("👂", "on your ears", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🥶🧊🐧",
     "q": "Where do penguins live?",
     "opts": [("🏜️", "in the hot desert", 0),
              ("🧊", "where it is icy and cold", 1),
              ("🌋", "in a volcano", 0)]},
    {"wh": "where", "lvl": 2, "scene": "⚽⬇️🛏️",
     "q": "Where is the ball?",
     "opts": [("🛏️", "under the bed", 1), ("🏠", "on the roof", 0),
              ("🧊", "in the fridge", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🐸🪷",
     "q": "Where is the frog sitting?",
     "opts": [("🪷", "on the lily pad", 1), ("🌙", "on the moon", 0),
              ("🛒", "in the cart", 0)]},
    {"wh": "where", "lvl": 2, "scene": "😁🦷",
     "q": "Where are your teeth?",
     "opts": [("👟", "in your shoe", 0), ("👄", "in your mouth", 1),
              ("🎒", "in your backpack", 0)]},
    {"wh": "where", "lvl": 2, "scene": "❤️🫀",
     "q": "Where is your heart?",
     "opts": [("🦵", "in your leg", 0), ("🫁", "in your chest", 1),
              ("🖐️", "in your hand", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🥛🧊",
     "q": "Where do you keep milk so it stays cold?",
     "opts": [("🧊", "in the fridge", 1), ("🛏️", "under the bed", 0),
              ("🔥", "in the oven", 0)]},
    {"wh": "where", "lvl": 2, "scene": "✨🌌",
     "q": "Where do the stars come out?",
     "opts": [("🌃", "in the night sky", 1), ("🌊", "under the water", 0),
              ("🏫", "at school", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🤴🏰",
     "q": "Where does a king live?",
     "opts": [("🏰", "in a castle", 1), ("⛺", "in a tent", 0),
              ("🚌", "on a bus", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🏴‍☠️⛵",
     "q": "Where do pirates sail their ship?",
     "opts": [("🌊", "on the sea", 1), ("🛣️", "on the road", 0),
              ("🏫", "at school", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🧥🪝",
     "q": "Where do you hang your coat?",
     "opts": [("🪝", "on a hook", 1), ("🧊", "in the fridge", 0),
              ("🛁", "in the bathtub", 0)]},
    {"wh": "where", "lvl": 2, "scene": "🍞🥐",
     "q": "Where do you buy fresh bread and cakes?",
     "opts": [("🥐", "at the bakery", 1), ("🏥", "at the hospital", 0),
              ("⛽", "at the gas station", 0)]},

    # ════════════════════════ WHY ════════════════════════
    # level 1
    {"wh": "why", "lvl": 1, "scene": "👦🧥❄️",
     "q": "Why is the boy wearing a coat?",
     "opts": [("❄️", "because it is cold", 1),
              ("☀️", "because it is hot", 0),
              ("🏊", "because he is swimming", 0)],
     "teach": "WHY answers start with BECAUSE."},
    {"wh": "why", "lvl": 1, "scene": "👧😢🍦",
     "q": "Why is the girl crying?",
     "opts": [("🎉", "because it is her birthday", 0),
              ("🍦", "because her ice cream fell down", 1),
              ("📗", "because the book is green", 0)]},
    {"wh": "why", "lvl": 1, "scene": "☔🌧️",
     "q": "Why do you open an umbrella?",
     "opts": [("🌧️", "because it is raining", 1),
              ("🍕", "because you are hungry", 0),
              ("💤", "because you are sleepy", 0)]},
    {"wh": "why", "lvl": 1, "scene": "🐶💦",
     "q": "Why is the dog wet?",
     "opts": [("📺", "because he watched TV", 0),
              ("🌧️", "because he was out in the rain", 1),
              ("🦴", "because he ate a bone", 0)]},
    {"wh": "why", "lvl": 1, "scene": "👦😂🤡",
     "q": "Why is the boy laughing?",
     "opts": [("🤡", "because the clown is funny", 1),
              ("😢", "because he is sad", 0),
              ("🥶", "because he is cold", 0)]},
    {"wh": "why", "lvl": 1, "scene": "😎☀️",
     "q": "Why is the girl wearing sunglasses?",
     "opts": [("☀️", "because the sun is very bright", 1),
              ("🌙", "because it is night time", 0),
              ("🍝", "because she loves spaghetti", 0)]},
    {"wh": "why", "lvl": 1, "scene": "👦💤🛏️",
     "q": "Why is the boy going to bed?",
     "opts": [("😴", "because he is tired", 1),
              ("⚽", "because he wants to play", 0),
              ("🍽️", "because he is hungry", 0)]},
    {"wh": "why", "lvl": 1, "scene": "👶😭🍼",
     "q": "Why is the baby crying?",
     "opts": [("🍼", "because she is hungry", 1),
              ("🎨", "because she painted a picture", 0),
              ("🚗", "because the car is red", 0)]},
    {"wh": "why", "lvl": 1, "scene": "👏🎭",
     "q": "Why is everyone clapping?",
     "opts": [("🎭", "because the show was great", 1),
              ("🥶", "because their hands are cold", 0),
              ("💤", "because they are sleepy", 0)]},
    {"wh": "why", "lvl": 1, "scene": "🏃💨🚌",
     "q": "Why is the boy running so fast?",
     "opts": [("🚌", "because the bus is about to leave", 1),
              ("🛏️", "because he loves his bed", 0),
              ("🧀", "because cheese is yellow", 0)]},
    {"wh": "why", "lvl": 1, "scene": "🥾💦",
     "q": "Why is the girl wearing rain boots?",
     "opts": [("💦", "because there are puddles outside", 1),
              ("☀️", "because it is sunny and dry", 0),
              ("🎂", "because it is her birthday", 0)]},

    # level 2
    {"wh": "why", "lvl": 2, "scene": "🦷🪥✨",
     "q": "Why do you brush your teeth?",
     "opts": [("✨", "to keep them clean and healthy", 1),
              ("🎵", "to make music", 0),
              ("🚀", "to fly to the moon", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🚲⛑️",
     "q": "Why do you wear a helmet on a bike?",
     "opts": [("🎩", "to look fancy", 0),
              ("🛡️", "to keep your head safe", 1),
              ("🔥", "to stay warm", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🍽️⚡",
     "q": "Why do we eat food?",
     "opts": [("⚡", "because our body needs energy", 1),
              ("📏", "because plates are round", 0),
              ("🐟", "because fish can swim", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🚦✋",
     "q": "Why do we stop at a red light?",
     "opts": [("❤️", "because red is pretty", 0),
              ("🚗", "to stay safe from cars", 1),
              ("🍎", "because apples are red", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🧼🖐️🦠",
     "q": "Why do you wash your hands?",
     "opts": [("🦠", "to wash the germs away", 1),
              ("🖍️", "to draw a picture", 0),
              ("⏰", "to tell the time", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🌱💧",
     "q": "Why do we water the plants?",
     "opts": [("💧", "because plants need water to grow", 1),
              ("🎨", "to change their color", 0),
              ("🎵", "because they like to sing", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🚗🔒",
     "q": "Why do you wear a seatbelt in the car?",
     "opts": [("🛡️", "to keep you safe if the car stops fast", 1),
              ("😎", "to look cool", 0),
              ("🎵", "to listen to music", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🧴☀️🏖️",
     "q": "Why do you put on sunscreen at the beach?",
     "opts": [("☀️", "so the sun does not burn your skin", 1),
              ("🦈", "to keep sharks away", 0),
              ("🏰", "to build better sandcastles", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🐻❄️💤",
     "q": "Why do bears sleep all winter?",
     "opts": [("❄️", "because food is hard to find in winter", 1),
              ("📺", "because they watched too much TV", 0),
              ("🎉", "because they had a big party", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🐦⬇️🌴",
     "q": "Why do some birds fly south in winter?",
     "opts": [("🌴", "because it is warmer there", 1),
              ("🎈", "because they like balloons", 0),
              ("📚", "because they go to school", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🤝😔",
     "q": "Why do you say sorry?",
     "opts": [("💛", "because you made a mistake and want to fix it", 1),
              ("🍦", "to get ice cream", 0),
              ("📣", "because it is loud", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🔌🔋",
     "q": "Why do you plug in the tablet?",
     "opts": [("🔋", "because the battery is empty", 1),
              ("🍕", "because it is hungry", 0),
              ("🛁", "because it needs a bath", 0)]},
    {"wh": "why", "lvl": 2, "scene": "✋👩‍🏫",
     "q": "Why do we raise our hand in class?",
     "opts": [("🗣️", "so everyone gets a turn to talk", 1),
              ("🪰", "to catch flies", 0),
              ("💪", "to show our muscles", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🍎💧",
     "q": "Why do you wash an apple before eating it?",
     "opts": [("🧼", "to clean off the dirt", 1),
              ("🎨", "to make it shiny red", 0),
              ("🐛", "because it is thirsty", 0)]},
    {"wh": "why", "lvl": 2, "scene": "💡🌙",
     "q": "Why do you turn on the lamp?",
     "opts": [("🌙", "because the room is dark", 1),
              ("🥵", "because you are hot", 0),
              ("🔊", "because it is quiet", 0)]},
    {"wh": "why", "lvl": 2, "scene": "🚸👀",
     "q": "Why do you look both ways before crossing the street?",
     "opts": [("🚗", "to check for cars coming", 1),
              ("🐦", "to count the birds", 0),
              ("👟", "to look at your shoes", 0)]},

    # ════════════════════════ HOW ════════════════════════
    # level 1
    {"wh": "how", "lvl": 1, "scene": "🐟🌊",
     "q": "How does a fish move?",
     "opts": [("🏊", "it swims", 1), ("🍎", "an apple", 0),
              ("🏫", "at school", 0)],
     "teach": "HOW asks about the WAY something is done."},
    {"wh": "how", "lvl": 1, "scene": "🐦☁️",
     "q": "How does a bird move?",
     "opts": [("🕊️", "it flies", 1), ("🛏️", "a bed", 0),
              ("👨‍🍳", "the chef", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🥣🍜",
     "q": "How do you eat soup?",
     "opts": [("🥄", "with a spoon", 1), ("👟", "with a shoe", 0),
              ("✏️", "with a pencil", 0)]},
    {"wh": "how", "lvl": 1, "scene": "📄✂️",
     "q": "How do you cut paper?",
     "opts": [("🥄", "with a spoon", 0), ("✂️", "with scissors", 1),
              ("🧦", "with a sock", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🚪🔒",
     "q": "How do you open a locked door?",
     "opts": [("🔑", "with a key", 1), ("🍌", "with a banana", 0),
              ("💤", "by sleeping", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🐍🌿",
     "q": "How does a snake move?",
     "opts": [("🐍", "it slides on its belly", 1),
              ("🍩", "a donut", 0), ("🏰", "a castle", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🦘🌾",
     "q": "How does a kangaroo move?",
     "opts": [("🦘", "it jumps", 1), ("📚", "a book", 0),
              ("👮", "the police officer", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🥤🧋",
     "q": "How do you drink a milkshake?",
     "opts": [("🥤", "with a straw", 1), ("🔑", "with a key", 0),
              ("🧤", "with mittens", 0)]},
    {"wh": "how", "lvl": 1, "scene": "💇🪮",
     "q": "How do you fix messy hair?",
     "opts": [("🪮", "with a hairbrush", 1), ("🍴", "with a fork", 0),
              ("⚽", "with a ball", 0)]},
    {"wh": "how", "lvl": 1, "scene": "🌱🚿",
     "q": "How do you water the plants?",
     "opts": [("🚿", "with a watering can", 1), ("✂️", "with scissors", 0),
              ("🧸", "with a teddy bear", 0)]},

    # level 2
    {"wh": "how", "lvl": 2, "scene": "🐌🍃",
     "q": "How does a snail move?",
     "opts": [("🐇", "very fast", 0), ("🐌", "very slowly", 1),
              ("✈️", "by flying", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🐇🥕",
     "q": "How does a rabbit move?",
     "opts": [("🦘", "it hops", 1), ("🏊", "it swims", 0),
              ("🐍", "it slides", 0)]},
    {"wh": "how", "lvl": 2, "scene": "⛄❄️",
     "q": "How do you make a snowman?",
     "opts": [("⚽", "roll big balls of snow", 1),
              ("🍳", "cook it in a pan", 0),
              ("🖍️", "color it with crayons", 0)]},
    {"wh": "how", "lvl": 2, "scene": "✈️☁️",
     "q": "How does an airplane travel?",
     "opts": [("☁️", "it flies through the sky", 1),
              ("🌊", "it sails on the water", 0),
              ("🛤️", "it rides on rails", 0)]},
    {"wh": "how", "lvl": 2, "scene": "⛵🌊",
     "q": "How does a boat travel?",
     "opts": [("🌊", "it sails on the water", 1),
              ("☁️", "it flies through the sky", 0),
              ("🛣️", "it drives on the road", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🥪🍞",
     "q": "How do you make a sandwich?",
     "opts": [("🍞", "put yummy things between two slices of bread", 1),
              ("🥤", "pour it in a cup", 0),
              ("❄️", "freeze it in the freezer", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🐘💦",
     "q": "How does an elephant drink water?",
     "opts": [("🐘", "with its long trunk", 1),
              ("🥤", "with a straw", 0),
              ("🥄", "with a spoon", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🕷️🕸️",
     "q": "How does a spider make its web?",
     "opts": [("🕸️", "with silk from its body", 1),
              ("🧶", "with yarn from the store", 0),
              ("✏️", "it draws it with a pencil", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🚸🚦",
     "q": "How do you cross the street safely?",
     "opts": [("👀", "look both ways, then walk", 1),
              ("🏃", "run as fast as you can", 0),
              ("🙈", "close your eyes and hop", 0)]},

    # HOW MANY — numbers!
    {"wh": "how", "lvl": 2, "scene": "🐶🐾",
     "q": "How many legs does a dog have?",
     "opts": [("4️⃣", "4", 1), ("2️⃣", "2", 0), ("6️⃣", "6", 0)],
     "teach": "HOW MANY asks for a NUMBER — count it!"},
    {"wh": "how", "lvl": 2, "scene": "🖐️🖐️",
     "q": "How many fingers are on two hands?",
     "opts": [("5️⃣", "5", 0), ("🔟", "10", 1), ("8️⃣", "8", 0)],
     "teach": "5 + 5 = 10!"},
    {"wh": "how", "lvl": 2, "scene": "🕷️🕸️",
     "q": "How many legs does a spider have?",
     "opts": [("6️⃣", "6", 0), ("8️⃣", "8", 1), ("🔟", "10", 0)]},
    {"wh": "how", "lvl": 2, "scene": "📅7️⃣",
     "q": "How many days are in a week?",
     "opts": [("7️⃣", "7", 1), ("5️⃣", "5", 0), ("🔟", "10", 0)]},
    {"wh": "how", "lvl": 2, "scene": "📆🗓️",
     "q": "How many months are in a year?",
     "opts": [("1️⃣2️⃣", "12", 1), ("🔟", "10", 0), ("2️⃣0️⃣", "20", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🚗🛞",
     "q": "How many wheels does a car have?",
     "opts": [("4️⃣", "4", 1), ("3️⃣", "3", 0), ("6️⃣", "6", 0)]},
    {"wh": "how", "lvl": 2, "scene": "👀😊",
     "q": "How many eyes do you have?",
     "opts": [("2️⃣", "2", 1), ("1️⃣", "1", 0), ("3️⃣", "3", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🦶🦶",
     "q": "How many toes are on both feet?",
     "opts": [("🔟", "10", 1), ("5️⃣", "5", 0), ("2️⃣0️⃣", "20", 0)],
     "teach": "5 toes + 5 toes = 10 toes!"},
    {"wh": "how", "lvl": 2, "scene": "⬡",
     "q": "How many sides does a hexagon have?",
     "opts": [("6️⃣", "6", 1), ("5️⃣", "5", 0), ("8️⃣", "8", 0)],
     "teach": "Hex- means 6. A hexagon has 6 sides, like a honeycomb!"},
    {"wh": "how", "lvl": 2, "scene": "🕐⏱️",
     "q": "How many minutes are in one hour?",
     "opts": [("6️⃣0️⃣", "60", 1), ("3️⃣0️⃣", "30", 0), ("💯", "100", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🌞🌙",
     "q": "How many hours are in one day?",
     "opts": [("2️⃣4️⃣", "24", 1), ("1️⃣2️⃣", "12", 0), ("6️⃣0️⃣", "60", 0)]},
    {"wh": "how", "lvl": 2, "scene": "🐶🐶",
     "q": "How many legs do 2 dogs have? 4 + 4 = ?",
     "opts": [("8️⃣", "8", 1), ("6️⃣", "6", 0), ("4️⃣", "4", 0)]},
    {"wh": "how", "lvl": 2, "scene": "💵🪙",
     "q": "How many cents are in one dollar?",
     "opts": [("💯", "100", 1), ("🔟", "10", 0), ("5️⃣0️⃣", "50", 0)]},
]

STORIES = [
    {"title": "The 5 Red Balloons", "emoji": "🎈",
     "text": "Sam has 5 red balloons. He is playing at the park. "
             "POP! 2 balloons pop on a tree branch. "
             "Sam laughs because the pop sound is so silly.",
     "qs": [
         {"wh": "who", "q": "Who has the balloons?",
          "opts": [("🧒", "Sam", 1), ("👵", "Grandma", 0),
                   ("👨‍🍳", "the chef", 0)]},
         {"wh": "where", "q": "Where is Sam playing?",
          "opts": [("🏫", "at school", 0), ("🛝", "at the park", 1),
                   ("🏪", "at the store", 0)]},
         {"wh": "why", "q": "Why does Sam laugh?",
          "opts": [("🔊", "because the pop sound is silly", 1),
                   ("🍦", "because he has ice cream", 0),
                   ("🌧️", "because it is raining", 0)]},
         {"wh": "how", "q": "How many balloons are left? 5 − 2 = ?",
          "opts": [("3️⃣", "3", 1), ("2️⃣", "2", 0), ("5️⃣", "5", 0)],
          "teach": "5 take away 2 leaves 3!"},
     ]},

    {"title": "10 Cookies for Grandma", "emoji": "🍪",
     "text": "Grandma bakes 10 cookies in the kitchen. "
             "The dog sneaks in and eats 4 cookies! "
             "The dog is happy because cookies are yummy.",
     "qs": [
         {"wh": "who", "q": "Who bakes the cookies?",
          "opts": [("🐶", "the dog", 0), ("👵", "Grandma", 1),
                   ("🧑‍🚒", "the firefighter", 0)]},
         {"wh": "where", "q": "Where does Grandma bake?",
          "opts": [("🍳", "in the kitchen", 1), ("🛝", "at the park", 0),
                   ("🚌", "on the bus", 0)]},
         {"wh": "what", "q": "What does the dog eat?",
          "opts": [("🍪", "cookies", 1), ("🥕", "carrots", 0),
                   ("🧦", "a sock", 0)]},
         {"wh": "how", "q": "How many cookies are left? 10 − 4 = ?",
          "opts": [("6️⃣", "6", 1), ("4️⃣", "4", 0), ("7️⃣", "7", 0)],
          "teach": "10 take away 4 leaves 6!"},
     ]},

    {"title": "Rocket Countdown", "emoji": "🚀",
     "text": "Mia the astronaut sits in her rocket. "
             "She counts down: 5… 4… 3… 2… 1… BLAST OFF! "
             "The rocket zooms up very fast, all the way to the moon. "
             "Mia wears a helmet because there is no air in space.",
     "qs": [
         {"wh": "who", "q": "Who is in the rocket?",
          "opts": [("🧑‍🚀", "Mia the astronaut", 1),
                   ("👨‍🍳", "the chef", 0), ("🐶", "a dog", 0)]},
         {"wh": "where", "q": "Where does the rocket go?",
          "opts": [("🌕", "to the moon", 1), ("🏫", "to school", 0),
                   ("🌊", "under the sea", 0)]},
         {"wh": "why", "q": "Why does Mia wear a helmet?",
          "opts": [("💨", "because there is no air in space", 1),
                   ("🎩", "because it looks fancy", 0),
                   ("🌧️", "because it is raining", 0)]},
         {"wh": "how", "q": "How does the rocket move?",
          "opts": [("⚡", "very fast, straight up", 1),
                   ("🐌", "very slowly", 0),
                   ("🏊", "it swims", 0)]},
         {"wh": "what", "q": "What number comes after 3 in a countdown? 3… ?",
          "opts": [("2️⃣", "2", 1), ("4️⃣", "4", 0), ("5️⃣", "5", 0)],
          "teach": "A countdown goes DOWN: 5, 4, 3, 2, 1!"},
     ]},

    {"title": "Bus Number 7", "emoji": "🚌",
     "text": "Ben drives bus number 7 to school. "
             "6 kids get on at the first stop. "
             "2 kids get off at the second stop. "
             "The kids ride the bus because school is far away.",
     "qs": [
         {"wh": "who", "q": "Who drives the bus?",
          "opts": [("🧒", "the kids", 0), ("🧑‍✈️", "Ben", 1),
                   ("👵", "Grandma", 0)]},
         {"wh": "where", "q": "Where is the bus going?",
          "opts": [("🏫", "to school", 1), ("🌕", "to the moon", 0),
                   ("🏖️", "to the beach", 0)]},
         {"wh": "why", "q": "Why do the kids ride the bus?",
          "opts": [("📏", "because school is far away", 1),
                   ("🍕", "because they love pizza", 0),
                   ("💤", "because they are sleepy", 0)]},
         {"wh": "how", "q": "How many kids are on the bus now? 6 − 2 = ?",
          "opts": [("4️⃣", "4", 1), ("6️⃣", "6", 0), ("8️⃣", "8", 0)],
          "teach": "6 kids got on, 2 got off: 6 − 2 = 4."},
     ]},

    {"title": "100 Busy Ants", "emoji": "🐜",
     "text": "100 ants live under the ground. "
             "Today 50 ants march out to find food. "
             "Each ant carries 1 leaf back home. "
             "They store the leaves because winter is coming.",
     "qs": [
         {"wh": "who", "q": "Who is marching to find food?",
          "opts": [("🐜", "the ants", 1), ("🐘", "the elephants", 0),
                   ("🧒", "the kids", 0)]},
         {"wh": "where", "q": "Where do the ants live?",
          "opts": [("⬇️", "under the ground", 1), ("☁️", "in the clouds", 0),
                   ("🛏️", "in a bed", 0)]},
         {"wh": "why", "q": "Why do the ants store leaves?",
          "opts": [("❄️", "because winter is coming", 1),
                   ("🎨", "because leaves are pretty", 0),
                   ("⚽", "to play a game", 0)]},
         {"wh": "how", "q": "How many ants stay home? 100 − 50 = ?",
          "opts": [("5️⃣0️⃣", "50", 1), ("🔟", "10", 0),
                   ("1️⃣0️⃣0️⃣", "100", 0)],
          "teach": "100 take away 50 is 50 — half of them!"},
     ]},

    {"title": "The Dinosaur Museum", "emoji": "🦕",
     "text": "Leo and his dad visit the dinosaur museum. "
             "They see 3 giant skeletons. "
             "The T-rex skeleton has about 60 teeth! "
             "Leo cannot touch the bones because fossils are very old "
             "and can break.",
     "qs": [
         {"wh": "who", "q": "Who goes to the museum with Leo?",
          "opts": [("👨", "his dad", 1), ("👵", "his grandma", 0),
                   ("👩‍🏫", "his teacher", 0)]},
         {"wh": "where", "q": "Where are Leo and Dad?",
          "opts": [("🦕", "at the dinosaur museum", 1),
                   ("🏊", "at the pool", 0), ("🛒", "at the store", 0)]},
         {"wh": "why", "q": "Why can't Leo touch the bones?",
          "opts": [("🦴", "because fossils are old and can break", 1),
                   ("🥶", "because the bones are too cold", 0),
                   ("👻", "because the bones are scary", 0)]},
         {"wh": "how", "q": "How many teeth does the T-rex skeleton have?",
          "opts": [("6️⃣0️⃣", "about 60", 1), ("6️⃣", "about 6", 0),
                   ("💯", "about 100", 0)]},
         {"wh": "what", "q": "What do Leo and Dad see at the museum?",
          "opts": [("🦴", "3 giant skeletons", 1), ("🐟", "3 goldfish", 0),
                   ("🚗", "3 race cars", 0)]},
     ]},

    {"title": "Pizza Night", "emoji": "🍕",
     "text": "It is pizza night! Mom cuts the pizza into 8 slices. "
             "There are 4 people in the family. "
             "Everyone gets the same number of slices. "
             "Mom cuts the pizza so everyone gets a fair share.",
     "qs": [
         {"wh": "who", "q": "Who cuts the pizza?",
          "opts": [("👩", "Mom", 1), ("👶", "the baby", 0),
                   ("🐶", "the dog", 0)]},
         {"wh": "what", "q": "What does the family eat?",
          "opts": [("🍕", "pizza", 1), ("🥣", "soup", 0),
                   ("🥗", "salad", 0)]},
         {"wh": "why", "q": "Why does Mom cut the pizza into slices?",
          "opts": [("🤝", "so everyone gets a fair share", 1),
                   ("🎨", "to make it pretty", 0),
                   ("❄️", "to make it cold", 0)]},
         {"wh": "how", "q": "How many slices does each person get? 8 ÷ 4 = ?",
          "opts": [("2️⃣", "2", 1), ("4️⃣", "4", 0), ("8️⃣", "8", 0)],
          "teach": "8 slices shared by 4 people: 8 ÷ 4 = 2 each!"},
     ]},

    {"title": "The Lost Kitten", "emoji": "🐱",
     "text": "Ava hears a tiny meow outside. "
             "A little kitten is hiding under the porch! "
             "It hid there because the thunder was loud and scary. "
             "Ava brings the kitten a bowl of milk. "
             "The kitten drinks it all in 2 minutes.",
     "qs": [
         {"wh": "who", "q": "Who hears the tiny meow?",
          "opts": [("👧", "Ava", 1), ("👮", "the police officer", 0),
                   ("🧑‍🚀", "an astronaut", 0)]},
         {"wh": "where", "q": "Where is the kitten hiding?",
          "opts": [("🏠", "under the porch", 1), ("🌳", "in a tree", 0),
                   ("🛒", "in a shopping cart", 0)]},
         {"wh": "why", "q": "Why did the kitten hide?",
          "opts": [("⛈️", "because the thunder was loud and scary", 1),
                   ("🎮", "because it was playing a game", 0),
                   ("☀️", "because it was too sunny", 0)]},
         {"wh": "what", "q": "What does Ava bring the kitten?",
          "opts": [("🥛", "a bowl of milk", 1), ("🍕", "a pizza", 0),
                   ("⚽", "a soccer ball", 0)]},
         {"wh": "how", "q": "How fast does the kitten drink the milk?",
          "opts": [("2️⃣", "in 2 minutes", 1), ("🕐", "in 2 hours", 0),
                   ("📅", "in 2 days", 0)]},
     ]},

    {"title": "Train Number 9", "emoji": "🚂",
     "text": "Train number 9 is going to the city. "
             "It has 3 cars, and each car has 20 seats. "
             "The conductor checks everyone's ticket. "
             "The whistle blows to tell people the train is leaving.",
     "qs": [
         {"wh": "who", "q": "Who checks the tickets?",
          "opts": [("🎫🧑", "the conductor", 1), ("👨‍🍳", "the chef", 0),
                   ("🐱", "a cat", 0)]},
         {"wh": "where", "q": "Where is the train going?",
          "opts": [("🏙️", "to the city", 1), ("🌕", "to the moon", 0),
                   ("🌊", "under the sea", 0)]},
         {"wh": "why", "q": "Why does the whistle blow?",
          "opts": [("📣", "to tell people the train is leaving", 1),
                   ("🎵", "because the train likes music", 0),
                   ("🍦", "to order ice cream", 0)]},
         {"wh": "how", "q": "How many seats are on the train? 3 × 20 = ?",
          "opts": [("6️⃣0️⃣", "60", 1), ("2️⃣3️⃣", "23", 0),
                   ("3️⃣0️⃣", "30", 0)],
          "teach": "3 cars with 20 seats each: 3 × 20 = 60 seats!"},
     ]},

    {"title": "The Snow Day", "emoji": "⛄",
     "text": "School is closed today because too much snow fell last night. "
             "Maya and her brother build a snowman with 3 big snowballs. "
             "They give him a carrot for a nose. "
             "The 2 kids wear all 4 of their mittens.",
     "qs": [
         {"wh": "why", "q": "Why is school closed?",
          "opts": [("❄️", "because too much snow fell", 1),
                   ("🎂", "because it is a birthday", 0),
                   ("🦁", "because a lion escaped", 0)]},
         {"wh": "who", "q": "Who builds the snowman with Maya?",
          "opts": [("👦", "her brother", 1), ("👩‍🏫", "her teacher", 0),
                   ("🧑‍🚒", "a firefighter", 0)]},
         {"wh": "what", "q": "What is the snowman's nose?",
          "opts": [("🥕", "a carrot", 1), ("🍌", "a banana", 0),
                   ("✏️", "a pencil", 0)]},
         {"wh": "how", "q": "How many snowballs make the snowman?",
          "opts": [("3️⃣", "3", 1), ("2️⃣", "2", 0), ("5️⃣", "5", 0)]},
         {"wh": "how", "q": "How many mittens do the 2 kids wear? 2 × 2 = ?",
          "opts": [("4️⃣", "4", 1), ("2️⃣", "2", 0), ("6️⃣", "6", 0)],
          "teach": "Each kid has 2 hands: 2 kids × 2 mittens = 4!"},
     ]},

    {"title": "Apple Picking Day", "emoji": "🍎",
     "text": "Zoe goes apple picking at the orchard. "
             "She picks 24 shiny red apples. "
             "She puts 6 apples in each basket. "
             "Zoe uses a ladder because the best apples grow up high.",
     "qs": [
         {"wh": "who", "q": "Who is picking apples?",
          "opts": [("👧", "Zoe", 1), ("🤴", "the king", 0),
                   ("🧑‍🔬", "a scientist", 0)]},
         {"wh": "where", "q": "Where does Zoe pick apples?",
          "opts": [("🌳", "at the orchard", 1), ("🏥", "at the hospital", 0),
                   ("🛝", "at the playground", 0)]},
         {"wh": "why", "q": "Why does Zoe use a ladder?",
          "opts": [("⬆️", "because the best apples grow up high", 1),
                   ("🎪", "because she is in the circus", 0),
                   ("🐜", "because she is afraid of ants", 0)]},
         {"wh": "how", "q": "How many baskets does Zoe fill? 24 ÷ 6 = ?",
          "opts": [("4️⃣", "4", 1), ("6️⃣", "6", 0), ("3️⃣", "3", 0)],
          "teach": "24 apples, 6 in each basket: 24 ÷ 6 = 4 baskets!"},
     ]},

    {"title": "Beep the Robot", "emoji": "🤖",
     "text": "Maya built a robot named Beep. "
             "Beep cleans 5 rooms, and each room takes 10 minutes. "
             "After cleaning, Beep goes beep-beep-beep! "
             "He beeps because his battery is almost empty.",
     "qs": [
         {"wh": "who", "q": "Who built Beep?",
          "opts": [("👧", "Maya", 1), ("🧑‍🚀", "an astronaut", 0),
                   ("👮", "a police officer", 0)]},
         {"wh": "what", "q": "What does Beep do?",
          "opts": [("🧹", "he cleans rooms", 1), ("🍳", "he cooks eggs", 0),
                   ("🎸", "he plays guitar", 0)]},
         {"wh": "why", "q": "Why does Beep go beep-beep-beep?",
          "opts": [("🔋", "because his battery is almost empty", 1),
                   ("🎵", "because he is singing a song", 0),
                   ("🐤", "because he saw a bird", 0)]},
         {"wh": "how", "q": "How long does Beep clean in all? 5 × 10 = ?",
          "opts": [("5️⃣0️⃣", "50 minutes", 1), ("1️⃣5️⃣", "15 minutes", 0),
                   ("🔟", "10 minutes", 0)],
          "teach": "5 rooms × 10 minutes = 50 minutes!"},
     ]},

    {"title": "Ocean Explorers", "emoji": "🐠",
     "text": "Captain Lin drives a little yellow submarine. "
             "It dives 100 meters under the sea. "
             "The lights are on because it is very dark deep down. "
             "Out the window they see an octopus with 8 arms!",
     "qs": [
         {"wh": "who", "q": "Who drives the submarine?",
          "opts": [("🧑‍✈️", "Captain Lin", 1), ("👵", "Grandma", 0),
                   ("🦈", "a shark", 0)]},
         {"wh": "where", "q": "Where does the submarine go?",
          "opts": [("🌊", "deep under the sea", 1), ("☁️", "up in the clouds", 0),
                   ("🏜️", "into the desert", 0)]},
         {"wh": "why", "q": "Why are the lights on?",
          "opts": [("🌑", "because it is very dark deep down", 1),
                   ("🎉", "because it is a party", 0),
                   ("📺", "to watch a movie", 0)]},
         {"wh": "how", "q": "How deep does the submarine dive?",
          "opts": [("💯", "100 meters", 1), ("🔟", "10 meters", 0),
                   ("1️⃣", "1 meter", 0)]},
         {"wh": "what", "q": "What do they see out the window?",
          "opts": [("🐙", "an octopus with 8 arms", 1),
                   ("🚂", "a train with 8 cars", 0),
                   ("🐘", "an elephant with 8 trunks", 0)]},
     ]},

    {"title": "The Birthday Cake", "emoji": "🎂",
     "text": "Today Ben turns 7 years old! "
             "Grandma bakes him a chocolate cake. "
             "She puts 7 candles on top. "
             "Ben blows out the candles to make a birthday wish.",
     "qs": [
         {"wh": "who", "q": "Who bakes the cake?",
          "opts": [("👵", "Grandma", 1), ("👦", "Ben", 0),
                   ("🧑‍🚒", "the firefighter", 0)]},
         {"wh": "what", "q": "What kind of cake is it?",
          "opts": [("🍫", "chocolate", 1), ("🍓", "strawberry", 0),
                   ("🥕", "carrot", 0)]},
         {"wh": "why", "q": "Why does Ben blow out the candles?",
          "opts": [("🌠", "to make a birthday wish", 1),
                   ("🥶", "because the cake is too hot", 0),
                   ("💨", "to practice blowing", 0)]},
         {"wh": "how", "q": "How many candles will Ben have next year? 7 + 1 = ?",
          "opts": [("8️⃣", "8", 1), ("7️⃣", "7", 0), ("6️⃣", "6", 0)],
          "teach": "Next birthday he turns 8, so 8 candles!"},
     ]},

    {"title": "Market Day", "emoji": "🥕",
     "text": "Farmer Jo brings carrots to the market. "
             "In the morning she sells 30 carrots. "
             "In the afternoon she sells 20 more. "
             "People buy them because the carrots were picked fresh today.",
     "qs": [
         {"wh": "who", "q": "Who sells the carrots?",
          "opts": [("🧑‍🌾", "Farmer Jo", 1), ("🧑‍✈️", "a pilot", 0),
                   ("🤴", "the king", 0)]},
         {"wh": "where", "q": "Where does Farmer Jo sell carrots?",
          "opts": [("🏪", "at the market", 1), ("🏊", "at the pool", 0),
                   ("🚀", "in a rocket", 0)]},
         {"wh": "why", "q": "Why do people buy her carrots?",
          "opts": [("🌱", "because they were picked fresh today", 1),
                   ("🎨", "because they are purple", 0),
                   ("🎵", "because they can sing", 0)]},
         {"wh": "how", "q": "How many carrots does she sell in all? 30 + 20 = ?",
          "opts": [("5️⃣0️⃣", "50", 1), ("3️⃣0️⃣", "30", 0),
                   ("6️⃣0️⃣", "60", 0)],
          "teach": "30 in the morning + 20 in the afternoon = 50 carrots!"},
     ]},
]

# All 50 US states and their capitals, alphabetical by state.
STATES = [
    ("Alabama", "Montgomery"), ("Alaska", "Juneau"), ("Arizona", "Phoenix"),
    ("Arkansas", "Little Rock"), ("California", "Sacramento"),
    ("Colorado", "Denver"), ("Connecticut", "Hartford"),
    ("Delaware", "Dover"), ("Florida", "Tallahassee"), ("Georgia", "Atlanta"),
    ("Hawaii", "Honolulu"), ("Idaho", "Boise"), ("Illinois", "Springfield"),
    ("Indiana", "Indianapolis"), ("Iowa", "Des Moines"), ("Kansas", "Topeka"),
    ("Kentucky", "Frankfort"), ("Louisiana", "Baton Rouge"),
    ("Maine", "Augusta"), ("Maryland", "Annapolis"),
    ("Massachusetts", "Boston"), ("Michigan", "Lansing"),
    ("Minnesota", "St. Paul"), ("Mississippi", "Jackson"),
    ("Missouri", "Jefferson City"), ("Montana", "Helena"),
    ("Nebraska", "Lincoln"), ("Nevada", "Carson City"),
    ("New Hampshire", "Concord"), ("New Jersey", "Trenton"),
    ("New Mexico", "Santa Fe"), ("New York", "Albany"),
    ("North Carolina", "Raleigh"), ("North Dakota", "Bismarck"),
    ("Ohio", "Columbus"), ("Oklahoma", "Oklahoma City"),
    ("Oregon", "Salem"), ("Pennsylvania", "Harrisburg"),
    ("Rhode Island", "Providence"), ("South Carolina", "Columbia"),
    ("South Dakota", "Pierre"), ("Tennessee", "Nashville"),
    ("Texas", "Austin"), ("Utah", "Salt Lake City"),
    ("Vermont", "Montpelier"), ("Virginia", "Richmond"),
    ("Washington", "Olympia"), ("West Virginia", "Charleston"),
    ("Wisconsin", "Madison"), ("Wyoming", "Cheyenne"),
]
