# Site settings
title: Notes
description: Personal notes and references
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mwestwood.github.io" # the base hostname & protocol for your site

permalink: pretty

defaults:
  - scope:
      path: "" # all files
      type: "pages"
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - CHANGELOG.md
  - MIGRATION.md
  - docker-compose.yml
  - Dockerfile

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/logo.png"

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 3
  previews: 2
  preview_words_before: 8
  preview_words_after: 8
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Sort order for navigation links
nav_sort: case_insensitive

# Show navigation error report
nav_error_report: false

liquid:
  error_mode: strict
  strict_filters: true

# Footer content
back_to_top: true
back_to_top_text: "Back to top"

author: mwestwood

footer_content: 'Personal notes site'

# Footer last edited timestamp
last_edit_timestamp: false

# Footer "Edit this page on GitHub" link
gh_edit_link: false

# Color scheme: "dark", "light"/nil (default), or a custom scheme
color_scheme: dark

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

sass:
  quiet_deps: true
  silence_deprecations: ['import']
